### ISSUE TITLE
[pdf] Switch PDF page rendering to an iterator format

### ISSUE THREAD

**Issue by frgfm** [mindee/doctr#1001]
As suggested by @mara004 in #1000, the PDF rendering is using a list comprehension which holds page processing while the rendering isn't complete:
https://github.com/mindee/doctr/blob/78c9105bb6c27c4a35ee9f601263da01668224b1/doctr/io/pdf.py#L45

This could be fixed by modifying it to yield the page and limit RAM usage:
```python
with pdfium.PdfDocument(file, password=password) as pdf:
    for img in pdf.render_topil(scale=scale, **kwargs): yield np.asarray(img)
```

**Comment by felixdittrich92** [comment]
Clean up the minor issues a bit :sweat_smile:

**Comment by felixdittrich92** [comment]
#1032

**Comment by felixdittrich92** [comment]
Outdated by #1240
