### ISSUE TITLE
Upcoming support for new model architectures

### ISSUE THREAD

**Issue by frgfm** [mindee/doctr#1007]
As discussed in several GH issues, docTR could very well welcome new architectures for OCR :+1: 
Let's use this issue to track this for the next release!

A few things to consider:
- docTR is not meant to make all architectures available. Let's focus on architectures that are reasonably sized and SOTA performances (or considered as a performance milestone for a given task).
- it is acceptable to start with the implementation with only 1 DL backend. Although, gradually, within the next releases, full support needs to be added.
- for faster iterations, training should be performed on synthetic data when available (perf will be pushed on private datasets later once the potential of the architecture is validated). A PR to add implementation for a given architecture should come with the exact args used in training to reproduce the training and the corresponding performances
- we **always have to** credit the rightful contributors: papers are always cited in docTR, and providing an implementation is meant not to be a copy paste of another implementation. However is part of the code of someone else is used, that author should be credited ("borrowed from", "inspired by", etc.)

Here is the list of envisioned models:

**Text detection**
- [ ] PAN - Pixel Aggregation Network ([paper](https://arxiv.org/pdf/1908.05900.pdf), [implementation](https://github.com/WenmuZhou/PAN.pytorch))

**Text recognition**
- [x] ViTSTR ([paper](https://arxiv.org/pdf/2105.08582.pdf), [implementation](https://github.com/roatienza/deep-text-recognition-benchmark)) #513 
- [x] ParSeq ([paper](https://arxiv.org/abs/2207.06966), [implementation](https://github.com/baudm/parseq)) #1003

**Comment by SkaarFacee** [comment]
I was hoping to be able to help with implementing the PAN model

**Comment by felixdittrich92** [comment]
If you want you can also work on this but as mentioned we would need to keep it as draft until the next release is done :)

**Comment by felixdittrich92** [comment]
- [ ] FAST ([paper](https://arxiv.org/pdf/2111.02394), [implementation](https://github.com/czczup/FAST))

Related: #1425 (TextNet backbone TF / PT)
