### ISSUE TITLE
Training not working on MacOS

### ISSUE THREAD

**Issue by dishant26** [mindee/doctr#1026]
### Bug description

Installed all the packages as mentioned in the README.
I was not getting this error on windows but as I switched to MacOS, I am getting this error.

### Code snippet to reproduce the bug

```
python3 references/detection/train_pytorch.py /Users/dishantpadalia/IITB/doctr_detection/train /Users/dishantpadalia/IITB/doctr_detection/val db_resnet50 --epochs 5 --device 0
```

### Error traceback

```
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: '/Users/dishantpadalia/opt/miniconda3/envs/doctr_env/lib/libcairo.so.2' (no such file), '/Users/dishantpadalia/opt/miniconda3/envs/doctr_env/bin/../lib/libcairo.so.2' (no such file), 'libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file), '/Users/dishantpadalia/IITB/doctr/libcairo.so.2' (no such file)
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: '/Users/dishantpadalia/opt/miniconda3/envs/doctr_env/lib/libcairo.2.dylib' (no such file), '/Users/dishantpadalia/opt/miniconda3/envs/doctr_env/bin/../lib/libcairo.2.dylib' (no such file), 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file), '/Users/dishantpadalia/IITB/doctr/libcairo.2.dylib' (no such file)
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: '/Users/dishantpadalia/opt/miniconda3/envs/doctr_env/lib/libcairo-2.dll' (no such file), '/Users/dishantpadalia/opt/miniconda3/envs/doctr_env/bin/../lib/libcairo-2.dll' (no such file), 'libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file), '/Users/dishantpadalia/IITB/doctr/libcairo-2.dll' (no such file)
```

### Environment

DocTR version: N/A
TensorFlow version: N/A
PyTorch version: 1.12.1 (torchvision 0.13.1)
OpenCV version: 4.6.0
OS: Mac OSX 12.5.1
Python version: 3.10.4
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): No
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

### Deep Learning backend

>>> from doctr.file_utils import is_tf_available, is_torch_available
>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: True
>>> print(f"is_torch_available: {is_torch_available()}")
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @dishant26 :wave:, thanks for reporting this.
We have had a similar issue on Windows could you please check if it is also helpful on Mac ?
#701

**Comment by dishant26** [comment]
Yeah this worked! Thanks!
I was the issue with conda on mac.
Install using these commands : https://anaconda.org/conda-forge/weasyprint
