### ISSUE TITLE
[Bug] LocalizationConfusion metric with use_polygons (rotation=True) results in enormous memory consumption

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#1042]
### Bug description

Ref.: #935 

duplicate:
- with broadcasting (default) it would kill every normal machine (FUNSD evaluation needs > 64GB RAM)
- without broadcasting it is ultra slow (but constant)

```
def polygon_iou(
    polys_1: np.ndarray, polys_2: np.ndarray, mask_shape: Tuple[int, int], use_broadcasting: bool = False
) -> np.ndarray:
    """Computes the IoU between two sets of rotated bounding boxes

    Args:
        polys_1: rotated bounding boxes of shape (N, 4, 2)
        polys_2: rotated bounding boxes of shape (M, 4, 2)
        mask_shape: spatial shape of the intermediate masks
        use_broadcasting: if set to True, leverage broadcasting speedup by consuming more memory

    Returns:
        the IoU matrix of shape (N, M)
    """

    if polys_1.ndim != 3 or polys_2.ndim != 3:
        raise AssertionError("expects boxes to be in format (N, 4, 2)")

    iou_mat: np.ndarray = np.zeros((polys_1.shape[0], polys_2.shape[0]), dtype=np.float32)

    if polys_1.shape[0] > 0 and polys_2.shape[0] > 0:
        if use_broadcasting:
            masks_1 = rbox_to_mask(polys_1, shape=mask_shape)
            masks_2 = rbox_to_mask(polys_2, shape=mask_shape)
            iou_mat = mask_iou(masks_1, masks_2)
        else:
            # Save memory by doing the computation for each pair
            for idx, b1 in enumerate(polys_1):
                m1 = _rbox_to_mask(b1, mask_shape)
                for _idx, b2 in enumerate(polys_2):
                    m2 = _rbox_to_mask(b2, mask_shape)
                    iou_mat[idx, _idx] = np.logical_and(m1, m2).sum() / np.logical_or(m1, m2).sum()

    return iou_mat
```

### Code snippet to reproduce the bug

python3  /home/felix/Desktop/doctr/references/detection/evaluate_pytorch.py db_mobilenet_v3_large --rotation

**Comment by frgfm** [comment]
I agree, it's a problem but I have no clue how we could get around it :/ 
Here is my point of view on the topic:
- the first computation is by far the fatest but considering the mask shape, it requires a lot of RAM. I don't think we can have an optimal alternative that would go as fast as this
- the second one is reducing the parallelism. However numpy is known to encode boolean tensors as higher precision data format, which increase mem consumption and slow down computation (those are not actually booleans). If that gets fixed, we might be able to speed this up

**Comment by felixdittrich92** [comment]
otherwise we check the underlying system with psutil and decide (with broadcasting or without) it's only relevant for scripts so i think this should be ok wdyt ?

**Comment by felixdittrich92** [comment]
@frgfm wdyt ?

**Comment by frgfm** [comment]
@felixdittrich92 what do you mean "relevant for scripts"? psutil won't bring much more information I think :thinking:
