### ISSUE TITLE
[models] Profiling models for temporal optimization

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#105]
Line Profiler [https://github.com/pyutils/line_profiler](https://github.com/pyutils/line_profiler)  is used to perform model profiling, to highlight the most time-consuming lines when our models are running.

For an OCRPredictor with a sar_vgg16_bn coupled with a db_resnet50, we have the following analysis:

- the whole recognition model (SAR)  accounts for 85% of the total execution time (OCR predictor)
- the whole detection model (DB)  accounts for 15% of the total execution time

More precisely:
- **Recognition task**: almost 100% of the time is spent inside the model (without pre/postprocessing). We have the following distribution inside the model: 22.5% for the feature extractor (VGG16 with bn), 17.5% for the encoder (2 LSTM layers with 512 hidden layers), and 60% for the decoder. The decoder has 2 main time-consuming tasks: a 31% goes to the lstm decoder (2 layers of stacked LSTM cells with 512 hidden layers), and a 62% goes to the attention module, and inside this module 87% of the time is spent in the conv2D operation (kernel 3x3, stride=1) which is encoding the feature map (N, H, W, feature_units) --> (N, H, W, attention_units=512). We can conclude for the recognition task that:

1. **27.5% of the total execution time (ocr end to end) is spent in this conv2D layer**, which can be reduced by **decreasing the number of attention units** from 512 to 256, maybe less.
2. 15% of the total execution time is spent in the encoder and another 16% of the total execution time is spent in the LSTM decoder. Thus, **LSTM layers accounts for more than 30% of the total execution time**. This can be improved by **reducing the number of encoding/decoding layers** from 2 to 1,  and **reducing the number of hidden rnn units inside the LSTM cells**  from 512 to 256 for instance.

It is important to highlight that **we have a significant leverage on the execution time of the whole model moving only 2 hyper-parameters: attention units and hidden units (almost 60% of the execution time end-to-end is directly impacted).**

- **Detection task**: 99% is spent inside the model and 1% for the post-processing. Inside the model, 65% are spent inside the feature extractor (Resnet50), which accounts for almost 10% in the whole model. This time can be reduced **using a lighter resnet such as resnet18 for instance.** The remaining 35% are spent in the pyramidal module and in the computing of the probability map.

**Comment by fg-mindee** [comment]
Thanks a lot for the investigation! By any chance, would you have the result on the CRNN as well?

I agree with your conclusion, we should try to make lighter versions of the SAR in the next release. Two questions though:
- with which input size did you conduct the study on the SAR? (by default 4 times bigger than the CRNN)
- are you positive they were pretrained ? (if not, it decreases the pre/post processing time)

**Comment by charlesmindee** [comment]
I am profiling the CRNN this afternoon, and I conducted the study with a 64 x 256 size for the SAR (default in the current pretrained models). Both models were pretrained.

**Comment by fg-mindee** [comment]
Closing this as the insights of this investigation have already been used!
