### ISSUE TITLE
Key Value Extraction

### ISSUE THREAD

**Issue by mmkulkarni09** [mindee/doctr#1085]
### 🚀 The feature

Request for a feature where we could get the key and its value as output in forms like documents.

### Motivation, pitch

I was working on Storing keys and values from forms,pdf etc and saving into rdbms,the current system dosent provide way to assign the key with values,so this feature would be of great help to all who are working on digitilisation of forms.

**Comment by felixdittrich92** [comment]
Hi @mmkulkarni09 :wave:,
thanks for opening the issue.

With key value extraction you mean something like LayoutLM ? 
Example: (scroll to the bottom)
https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv3/Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).ipynb

**Comment by mmkulkarni09** [comment]
Thanks for the reply @felixdittrich92,Can you Please suggest a way to directly use key-value parser on any forms by using pre-trained models?

**Comment by felixdittrich92** [comment]
KIE detection available in the next release
