### ISSUE TITLE
Colab tutorials are not running as expected

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#1089]
### Bug description

The tutorials are outdated and need to be update :
https://github.com/mindee/notebooks

- update installation
- other code is ok

**Comment by Hackathorn** [comment]
Concur... import of PILLOW versions conflict

**Comment by nikokks** [comment]
I have done a pull request for this repository.
It seems to work when we clear outputs and reload them

**Comment by felixdittrich92** [comment]
Hi @nikokks 👋
Thanks a lot i will check your PR today
