### ISSUE TITLE
NumPy userwarning(s) while importing doctr

### ISSUE THREAD

**Issue by pratheesh-prakash** [mindee/doctr#1104]
### Bug description

While importing doctr, I am getting Userwarning messages from numpy.

Expectation: No warning messages.

### Code snippet to reproduce the bug

```python
import doctr
```

### Error traceback

```
~/.venv/lib/python3.8/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
~/.venv/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
~/.venv/lib/python3.8/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
~/.venv/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
```

### Environment

DocTR version: 0.6.0
TensorFlow version: 2.9.0
PyTorch version: N/A (torchvision N/A)
OpenCV version: 4.6.0
OS: elementary OS 6.1 Jólnir
Python version: 3.8.10
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): N/A
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

### Deep Learning backend

is_tf_available: True

**Comment by felixdittrich92** [comment]
Hey @pratheesh-prakash 👋,

this seems to be a problem with your OS and numpy where we cannot much do.
