### ISSUE TITLE
16 bit precision support in predictors

### ISSUE THREAD

**Issue by Ryul0rd** [mindee/doctr#1112]
### 🚀 The feature

Currently, the various predictor classes such as `OCRPredictor` don't support 16 bit precision and it would be great if they did. The PyTorch flavor of predictors are just `nn.Module`s so you should be able to write 
```
model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True).half()
output = model(document_tensor.half())
```
and have it work but it doesn't.

### Motivation, pitch

Doing text detection and OCR on many documents is time consuming even with multiple high-end GPUs. 16 bit precision offers a nearly 2x speedup for free on supported GPUs. You can currently use 16 bit precision with the bare models but this is very cumbersome given the amount of pre- and post-processing involved in OCR.

**Comment by felixdittrich92** [comment]
Hey @Ryul0rd 👋,

Really great issue and excuse the late response.
I will work on this hopefully next week 👍
