### ISSUE TITLE
Documentation for running on docker

### ISSUE THREAD

**Issue by talesam** [mindee/doctr#1113]
### 🚀 The feature

I turn everything into docker, my applications, but I found the documentation in docker very shallow. I created an image, but is it enough to run? On the guide page there is a command to upload a docker-compose, but there is no docker-compose.yml file as an example.

### Motivation, pitch

If you need help I can provide something more complete, images in docker compiled in several architectures, but I noticed that the Dockerfile is very simple, it can be improved, already configuring a port, since you need one to be used, volume for persistence. I can create an example docker-compose.yml to use.

But I need more information, how do I run a test using docker?

**Comment by odulcy-mindee** [comment]
Hello @talesam ! :wave:
Thanks for this issue ! Are you talking about the `Dockerfile` at the root of this repository or about `docker-compose.yml` in the `api` folder ?
