### ISSUE TITLE
API docker build 

### ISSUE THREAD

**Issue by meliascosta** [mindee/doctr#1126]
### Bug description

I tried to run the command `make lock` but I get the following error: 

**Because doctr-api depends on python-doctr (>=0.7.0) which doesn't match any versions, version solving failed.**

It looks like the pyproject.toml file is already prepared to use version 0.7.0 but the latest version published on PyPI is 0.6.0

### Code snippet to reproduce the bug

```bash
make lock
```

### Error traceback

*Because doctr-api depends on python-doctr (>=0.7.0) which doesn't match any versions, version solving failed.

### Environment

DocTR version: N/A
TensorFlow version: N/A
PyTorch version: N/A (torchvision N/A)
OpenCV version: N/A
OS: Ubuntu 20.04.5 LTS
Python version: 3.9.7
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

### Deep Learning backend

Not applicable this is before installation

**Comment by odulcy-mindee** [comment]
Hello @meliascosta,

Thanks for this issue. Indeed, your diagnostic is correct:
> It looks like the pyproject.toml file is already prepared to use version 0.7.0 but the latest version published on PyPI is 0.6.0

We have not made a release on `PyPI` yet. I need to check with the team when we'll release it.

In the meantime, I fixed this problem in https://github.com/mindee/doctr/issues/1126
