### ISSUE TITLE
[encoding] Unify string encoding for datasets and models

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#115]
As of the latest commit, models are trained with a string encoder that is not particularly ordered (TF records). To clean all of this, I suggest the following:
- [x] Define pre-established vocab that we will use as encoders for your future models (#116)
- [ ] Address the topic of vocab mapping (converting an accented character to its raw version for instance)
- [x] Standardize dataset label encoding using a given vocab (#116)

On the topic of vocab definition, there are two aspects to consider: the character selection, their order in the vocab.

cc @charlesmindee

**Comment by fg-mindee** [comment]
So, here are a few suggestions:
```
import string
latin = string.digits + string.ascii_letters + string.punctuation + '°'
french = latin + 'àâéèêëîïôùûçÀÂÉÈËÎÏÔÙÛÇ'
```
For reference, the 'latin' vocab would yield:
```
In [3]: latin
Out[3]: '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~°'
```

For later, I think it would be useful to have:
```
currency = '£€¥¢฿'
```

**Comment by charlesmindee** [comment]
To address the 2nd point of the issue, I looked at Huggin Face Normalizer class:
[huggin face module-tokenizers.normalizers](https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#module-tokenizers.normalizers). 
The normalizers perform conversion to lower case, accent stripping, chinese characters removal, spaces removal and contains basic unicode normalizers: NFC/D, NFKC/D. The detection on chinese characters [here](https://github.com/huggingface/tokenizers/blob/master/tokenizers/src/normalizers/bert.rs) seems hardcoded, but t he rest of the techniques use classical high-level functions (equivalent of unicodedata.normalize('NFC/D'), .lowercase(), ...)

**Comment by fg-mindee** [comment]
Let's go with the option of having something specifying which alphabet is supported by which model in the document.
As of #238, we can now close this issue!
