### ISSUE TITLE
Reproducability : Different Results for Different Python Versions (3.8, 3.10)

### ISSUE THREAD

**Issue by khanfarhan10** [mindee/doctr#1153]
### Bug description

The bboxes obtained for a sample image are different across py3.10.9 & py3.8.13 even when the latest doctr installed.

### Code snippet to reproduce the bug

```python
MODEL = ocr_predictor(pretrained=True)
prediction = MODEL(img).export()
```

### Error traceback

NA

### Environment

(Will generate for both if relevant/asked)

### Deep Learning backend

tensorflow

**Comment by felixdittrich92** [comment]
Hi @khanfarhan10 👋,

Thanks for reporting this it would be great if you could attach an example Image and the different outputs (also some more information about TF version and Cuda)

**Comment by felixdittrich92** [comment]
Closing because: no response

I have tested it with two images on py3.8 and 3.10 with same results
