### ISSUE TITLE
Sar_Resnet31: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by khawar-islam** [mindee/doctr#1169]
### Bug description

I am training the `sar_resnet31` model [PyTorch version] on the Korean dataset. I have changed the vocab variable and just passed the fonts.

### Code snippet to reproduce the bug

`python3 train_pytorch.py sar_resnet31 --train_path /media/cvpr/CM_22/KR_2M/train --val_path /media/cvpr/CM_22/KR_2M/val --font "ko/NanumBarunGothicBold.ttf,ko/나눔손글씨 따악단단.ttf,ko/NanumBarunGothicLight.ttf,ko/나눔손글씨 딸에게 엄마가.ttf,ko/NanumBarunGothic.ttf,ko/나눔손글씨 또박또박.ttf,ko/NanumBarunGothicUltraLight.ttf,ko/나눔손글씨 마고체.ttf,ko/NanumBarunpenB.ttf,ko/나눔손글씨 맛있는체.ttf,ko/NanumBarunpenR.ttf,ko/나눔손글씨 몽돌.ttf,ko/NanumBrush.ttf,ko/나눔손글씨 무궁화.ttf,ko/NanumGothicBold.ttf,ko/나눔손글씨 무진장체.ttf,ko/NanumGothicExtraBold.ttf,ko/나눔손글씨 미니 손글씨.ttf,ko/NanumGothicLight.ttf,ko/나눔손글씨 미래나무.ttf,ko/NanumGothic.ttf,ko/나눔손글씨 바른정신.ttf,ko/NanumMyeongjoBold.ttf,ko/나눔손글씨 바른히피.ttf,ko/NanumMyeongjoExtraBold.ttf,ko/나눔손글씨 반짝반짝 별.ttf,ko/NanumMyeongjo.ttf,ko/나눔손글씨 배은혜체.ttf,ko/NanumPen.ttf,ko/나눔손글씨 백의의 천사.ttf,ko/NanumSquareB.ttf,ko/나눔손글씨 버드나무.ttf,ko/NanumSquareEB.ttf,ko/나눔손글씨 범솜체.ttf,ko/NanumSquareL.ttf,ko/나눔손글씨 부장님 눈치체.ttf,ko/NanumSquareRoundB.ttf,ko/나눔손글씨 북극성.ttf,ko/NanumSquareRoundEB.ttf,ko/나눔손글씨 비상체.ttf,ko/NanumSquareRoundL.ttf,ko/나눔손글씨 빵구니맘 손글씨.ttf,ko/NanumSquareRoundR.ttf,ko/나눔손글씨 사랑해 아들.ttf,ko/NanumSquareR.ttf,ko/나눔손글씨 상해찬미체.ttf,ko/나눔손글씨 끄트머리체.ttf,ko/나눔손글씨 성실체.ttf,ko/나눔손글씨 강부장님체.ttf,ko/ 나눔손글씨 세계적인 한글.ttf,ko/나눔손글씨 느릿느릿체.ttf,ko/나눔손글씨 세아체.ttf,ko/나눔손글씨 노력하는 동희.ttf,ko/나눔손글씨 아기사 랑체.ttf,ko/나눔손글씨 나무정원.ttf,ko/나눔손글씨 아름드리 꽃나무.ttf,ko/나눔손글씨 기쁨밝음.ttf,ko/나눔손글씨 아빠글씨.ttf,ko/나눔손글 씨 금은보화.ttf,ko/나눔손글씨 아빠의 연애편지.ttf,ko/나눔손글씨 고려글꼴.ttf,ko/나눔손글씨 아인맘 손글씨.ttf,ko/나눔손글씨 김유이체.ttf,ko/나눔손글씨 아줌마 자유.ttf,ko/나눔손글씨 대광유리.ttf,ko/나눔손글씨 안쌍체.ttf,ko/나눔손글씨 달의궤도.ttf,ko/나눔손글씨 암스테르담.ttf,ko/나눔손글씨 가람연꽃.ttf,ko/나눔손글씨 야근하는 김주임.ttf,ko/나눔손글씨 다채사랑.ttf,ko/나눔손글씨 야채장수 백금례.ttf,ko/나눔손글 씨 규리의 일기.ttf,ko/나눔손글씨 엄마사랑.ttf,ko/나눔손글씨 강인한 위로.ttf,ko/나눔손글씨 엉겅퀴체.ttf,ko/나눔손글씨 곰신체.ttf,ko/나눔 손글씨 여름글씨.ttf,ko/나눔손글씨 갈맷글.ttf,ko/나눔손글씨 연지체.ttf,ko/나눔손글씨 다진체.ttf,ko/나눔손글씨 열아홉의 반짝임.ttf,ko/나눔손글씨 다행체.ttf,ko/나눔손글씨 열일체.ttf,ko/나눔손글씨 꽃내음.ttf,ko/나눔손글씨 예당체.ttf,ko/나눔손글씨 나는 이겨낸다.ttf,ko/나눔손글씨 예쁜 민경체.ttf,ko/나눔손글씨 고딕 아니고 고딩.ttf,ko/나눔손글씨 옥비체.ttf,ko/나눔손글씨 다시 시작해.ttf,ko/나눔손글씨 와일드.ttf,ko/나눔손글씨 나의 아내 손글씨.ttf,ko/나눔손글씨 우리딸 손글씨.ttf,ko/나눔손글씨 고려글꼴.ttf,ko/나눔손글씨 의미있는 한글.ttf,ko/나눔손글 씨 달의궤도.ttf,ko/나눔손글씨 자부심지우.ttf,ko/나눔손글씨 따뜻한 작별.ttf" --batch_size 64 --epochs 10`

### Error traceback

```
Traceback (most recent call last):
  File "/media/cvpr/CM_22/doctr/references/recognition/train_pytorch.py", line 515, in <module>
    main(args)
  File "/media/cvpr/CM_22/doctr/references/recognition/train_pytorch.py", line 426, in main
    fit_one_epoch(model, train_loader, batch_transforms, optimizer, scheduler, mb, amp=args.amp)
  File "/media/cvpr/CM_22/doctr/references/recognition/train_pytorch.py", line 124, in fit_one_epoch
    train_loss = model(images, targets)["loss"]
  File "/home/cvpr/anaconda3/envs/pytesseract/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/cvpr/CM_22/doctr/doctr/models/recognition/sar/pytorch.py", line 249, in forward
    decoded_features = self.decoder(features, encoded, gt=None if target is None else gt)
  File "/home/cvpr/anaconda3/envs/pytesseract/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/cvpr/CM_22/doctr/doctr/models/recognition/sar/pytorch.py", line 156, in forward
    glimpse = self.attention_module(features, hidden_state)
  File "/home/cvpr/anaconda3/envs/pytesseract/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/cvpr/CM_22/doctr/doctr/models/recognition/sar/pytorch.py", line 68, in forward
    state_projection = self.state_conv(hidden_state)
  File "/home/cvpr/anaconda3/envs/pytesseract/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cvpr/anaconda3/envs/pytesseract/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cvpr/anaconda3/envs/pytesseract/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([64, 512, 1, 1], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 512, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    memory_format = Contiguous
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x55cda57b6ac0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 64, 512, 1, 1, 
    strideA = 512, 1, 1, 1, 
output: TensorDescriptor 0x55cd9d24fca0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 64, 512, 1, 1, 
    strideA = 512, 1, 1, 1, 
weight: FilterDescriptor 0x55cda57b1b80
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 512, 512, 1, 1, 
Pointer addresses: 
    input: 0x7fb84b1e0000
    output: 0x7fb7dbfa0000
    weight: 0x7fb967300000


```

### Environment

```
DocTR version: N/A
TensorFlow version: 2.6.0
PyTorch version: 1.13.1 (torchvision 0.14.1)
OpenCV version: 4.5.4
OS: Ubuntu 20.04.6 LTS
Python version: 3.9.12
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.6.124
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 515.86.01
cuDNN version: Could not collect
```

### Deep Learning backend

`True`

**Comment by felixdittrich92** [comment]
Hi @khawar-islam 👋,

Looks like your nvidia driver isn't installed correctly or pytorch ..please check this again. I was not able to reproduce the error.
