### ISSUE TITLE
Crop orientation model / images not moved to GPU memory

### ISSUE THREAD

**Issue by gnanads** [mindee/doctr#1174]
### Bug description

When I use predict the crop orientation model in GPU environment , I'm getting following 

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### Code snippet to reproduce the bug

import torch
import os
import cv2
os.environ["USE_TORCH"] = '1'
from doctr.models import crop_orientation_predictor

cuda = torch.cuda.is_available()
device = torch.device("cuda" if cuda else "cpu")

orientation_model = crop_orientation_predictor(pretrained=True).cuda()

image = cv2.imread("some_img.png")
image_2 = cv2.imread("test.png")
print(image.shape)
print(image_2.shape)

cropped_images = [image,image_2]

angle = orientation_model(cropped_images)

### Error traceback

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-170-e78366133c4e> in <module>
     16 
     17 cropped_images = [image,image_2]
---> 18 angle = orientation_model(cropped_images)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/opt/conda/lib/python3.7/site-packages/doctr/models/classification/predictor/pytorch.py in forward(self, crops)
     46         processed_batches = self.pre_processor(crops)
     47         _device = next(self.model.parameters()).device
---> 48         predicted_batches = [self.model(batch).to(device=_device) for batch in processed_batches]
     49 
     50         # Postprocess predictions

/opt/conda/lib/python3.7/site-packages/doctr/models/classification/predictor/pytorch.py in <listcomp>(.0)
     46         processed_batches = self.pre_processor(crops)
     47         _device = next(self.model.parameters()).device
---> 48         predicted_batches = [self.model(batch).to(device=_device) for batch in processed_batches]
     49 
     50         # Postprocess predictions

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/torchvision/models/mobilenetv3.py in forward(self, x)
    218 
    219     def forward(self, x: Tensor) -> Tensor:
--> 220         return self._forward_impl(x)
    221 
    222 

/opt/conda/lib/python3.7/site-packages/torchvision/models/mobilenetv3.py in _forward_impl(self, x)
    208 
    209     def _forward_impl(self, x: Tensor) -> Tensor:
--> 210         x = self.features(x)
    211 
    212         x = self.avgpool(x)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py in forward(self, input)
    202     def forward(self, input):
    203         for module in self:
--> 204             input = module(input)
    205         return input
    206 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py in forward(self, input)
    202     def forward(self, input):
    203         for module in self:
--> 204             input = module(input)
    205         return input
    206 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py in forward(self, input)
    461 
    462     def forward(self, input: Tensor) -> Tensor:
--> 463         return self._conv_forward(input, self.weight, self.bias)
    464 
    465 class Conv3d(_ConvNd):

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight, bias)
    458                             _pair(0), self.dilation, self.groups)
    459         return F.conv2d(input, weight, bias, self.stride,
--> 460                         self.padding, self.dilation, self.groups)
    461 
    462     def forward(self, input: Tensor) -> Tensor:

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### Environment

Collecting environment information...

DocTR version: v0.6.0
TensorFlow version: N/A
PyTorch version: 1.13.1+cu117 (torchvision 0.14.1+cu117)
OpenCV version: 4.7.0
OS: Debian GNU/Linux 10 (buster)
Python version: 3.7.10
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 470.57.02
cuDNN version: Could not collect

### Deep Learning backend

is_tf_available: False
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @gnanads 👋 ,

Thanks for reporting this.
The issue is already fixed in the `main` branch :)

**Comment by gnanads** [comment]
Thanks @felixdittrich92
