### ISSUE TITLE
Error when merging large crops

### ISSUE THREAD

**Issue by BenoitdeKersabiec** [mindee/doctr#1185]
The error is pretty obvious in this line

https://github.com/mindee/doctr/blob/57151161e16385e4e9ebf63503a88f319006f1c5/doctr/models/recognition/utils.py#L34
Returning b in both cases is probably a mistake. It should probably be

```python
    seq_len = min(len(a), len(b))
    if seq_len == 0:  # One sequence is empty, return the other
        return b if len(a) == 0 else a
```

**Comment by felixT2K** [comment]
Hey @BenoitdeKersabiec 👋🏼 ,

I will check this. Could you provide an example in the meanwhile ? :)

**Comment by felixdittrich92** [comment]
#1229
