### ISSUE TITLE
issue when using with multiprocessing

### ISSUE THREAD

**Issue by msaoudallah** [mindee/doctr#1207]
### Bug description

i have an issue which is i need to use `doctr` whithin a subprocess so that memory is released when the prossed is finished. my problem is when i start the inference from the PDF i get the following output 
![image](https://github.com/mindee/doctr/assets/6372325/cc9cf1d2-fa34-46b5-8f5c-66ca976bd4fe)

i have a flask server and when i send the first request to be processed this happens, but the subsequent requests complete successfully 
another note is i used this application within docker container and i don't have GPU 

 

### Code snippet to reproduce the bug

```python
with concurrent.futures.ProcessPoolExecutor(max_workers =8) as executor:
                    result = executor.submit(self.get_xml_custom, fileobj).result()
```
please note that this line is executed from parent class and the `self.get_xml_custom` is excuted from child class

### Error traceback

no errors just this line 

```
free(): invalid pointer
```

### Environment

DocTR version: v0.6.0
TensorFlow version: N/A
PyTorch version: 1.10.0+rocm4.2 (torchvision 0.11.1+rocm4.2)
OpenCV version: 4.6.0
OS: Debian GNU/Linux 11 (bullseye)
Python version: 3.8.16
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): No
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

### Deep Learning backend

is_tf_available: False
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @msaoudallah 👋,

Please try to set a env var to:
`DOCTR_MULTIPROCESSING_DISABLE=TRUE`

**Comment by msaoudallah** [comment]
hello @felixdittrich92 ,
can you please provide an example of how this would work ?  and would it help releasing memory after execution finish ?

**Comment by felixdittrich92** [comment]
Hey @msaoudallah 👋,
You can put `os.environ['DOCTR_MULTIPROCESSING_DISABLE'] = 'TRUE'` on top of your code. :)
If i remember it has solved a possible memory leak also but i am not 100% sure :)

**Comment by felixdittrich92** [comment]
Hi @msaoudallah 👋,
has this solved your issue ? :)

**Comment by Srini138** [comment]
Hi @felixdittrich92 I added the line of code you mentioned and deployed in AWS EC2 instance but it's taking more than a minute for single page document to get the result . I'm also using docker container not having GPU. Is there any other to approach to get rid of from this memory leakage

**Comment by felixdittrich92** [comment]
Hi @Srini138 :wave:,

which backend do you use (Pytorch/Tensorflow) ? 
Sounds like your problem is the inference latency have you tried to use smaller models ?
For example `crnn_mobilenet_v3_small` as recognition model and `db_mobilenet_v3_large` as detection model ? This will lower also the needed memory :)

**Comment by Srini138** [comment]
Hi @felixdittrich92 

Thanks for your response. I used light weight model at intial but for some of the noisy low pixel documents it couldn't able perform well so i switched to the default model `det_arch='db_resnet50', reco_arch='crnn_vgg16_bn'` . In local my inferencing latency doesn't even exceed around 50 seconds but after deployed in AWS EC2 instance there is a drastic change in inference latency . I am using default backend tensorflow and also I added based on AWS Lambda docTR documentation `os.environ['DOCTR_MULTIPROCESSING_DISABLE'] = True` and `os.environ['DOCTR_CACHE_DIR'] = 'weights/'` on top of code to restrict everytime downloading the model and saving it in weights folder and loading from there. How to resolve this latency issue any suggestions welcome

**Comment by felixdittrich92** [comment]
Could you share some more information about the instance type and some profiler logs maybe (necessary to debug possible memory leaks) ? :)
Have you tried to use mixed_float16 with Tensorflow? This should lower the memory footprint significant and also bring a little speedup

**Comment by Srini138** [comment]
Hi @felixdittrich92 
instance type is kubernetes cluster running in EKS . I am not using profiling in prod environment as it may give perfomance overhead. mixed precision on tensorflow how to use it for docTR inference code any suggestions on this

**Comment by felixdittrich92** [comment]
Hi @Srini138 please take a look at https://www.tensorflow.org/guide/mixed_precision

**Comment by mara004** [comment]
@msaoudallah Could you check if the memory leak also happens with image input, so we can rule out an issue with the pdf backend?

**Comment by msaoudallah** [comment]
@mara004 , i use `from_pdf` directly on the PDF file. i'm still having same leakage issue

**Comment by mara004** [comment]
@msaoudallah Can you test with 4e1985f, where doctr switched to the page-level renderer, e.g. using the current main branch? Previously `from_pdf()` would use pypdfium2's internal multiprocessing, which is not covered by `DOCTR_MULTIPROCESSING_DISABLE=TRUE`. I can imagine that nested multiprocessing is problematic.

Also, is this an actual leak, or just the problem that doctr stacks the rendered bitmaps in memory instead of releasing them iteratively (see https://github.com/mindee/doctr/discussions/1000) ?

**Comment by tvasenin** [comment]
@felixdittrich92 @msaoudallah We also have memory growth issues when using multiprocessing, and recent #1323 change seems to have fixed that!
While I don't fully understand how exactly did it help, I suggest you to try the latest nightly or execute your model call using `with torch.inference_mode:` context.

**Comment by felixdittrich92** [comment]
Hi @tvasenin thanks a lot for the feedback nice to hear 😄 

I cannot say much because i don't have a Mac.
Just a guess: in `inference_mode` everything under the hood is handled more static and with less write operations i think that's the reason why python's multiprocessing seems to work also on Mac systems less broken 😅


For visibility @odulcy-mindee 
So i will close it 👍
