### ISSUE TITLE
Detection Training using other Datasets is not added + Detection Training using pytorch is faulty

### ISSUE THREAD

**Issue by kasuba-badri-vishal** [mindee/doctr#1251]
### Bug description

Unable to implement Detection training using PyTorch as facing different kinds of errors for training form scratch using any model. The datasets were created according to the README file present in references/detection/ folder, but training is causing different errors.

When reverted the commit to December's commit, it started working but still the predictions even with pretrained model, are not properly oriented

### Code snippet to reproduce the bug

```
python references/detection/train_pytorch.py path/to/your/train_set path/to/your/val_set db_resnet50 --epochs 5 --device 0
```

### Error traceback

Multiple Errors

### Environment

DocTR version: v0.6.0
TensorFlow version: N/A
PyTorch version: 2.0.1+cu117 (torchvision 0.15.2+cu117)
OpenCV version: 4.7.0
OS: Ubuntu 22.04.1 LTS
Python version: 3.10.6
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

### Deep Learning backend

is_tf_available: False
is_torch_available: True

**Comment by felixT2K** [comment]
Hi @kasuba-badri-vishal 👋🏼 ,

Could you please use the main branch (docTR version: 0.6.1) and try it again ?
If the errors still exist please post them here :)

**Comment by felixdittrich92** [comment]
Hi @kasuba-badri-vishal :wave: Any updates ? :)

**Comment by kasuba-badri-vishal** [comment]
Worked once
