### ISSUE TITLE
Combine detection with (TrOCR) recognition models

### ISSUE THREAD

**Issue by Mohammed20201991** [mindee/doctr#1307]
### 🚀 The feature

As we can see that the [TrOCR](https://huggingface.co/microsoft/trocr-base-handwritten) model achieve State-of-the-art results for text recognition task and has limitation with line level it would be great to combine it with detection model such as `db_resnet50` or any other migrated model for [Hugging face format](https://huggingface.co/)

### Motivation, pitch

As there are a lot of valuable Historical Handwritten dataset (documents) and wanna digitize it in automation way

**Comment by felixdittrich92** [comment]
Hi @Mohammed20201991  👋 ,

You should take a look at https://github.com/kforcodeai/doctr-trocr 
Maybe @kforcodeai could update the space ? :)

**Comment by felixdittrich92** [comment]
@Mohammed20201991 Looks like we can close it ? :)
Otherwise let me know :+1:

**Comment by Mohammed20201991** [comment]
Dear @felixdittrich92 still has some issues if you can help in this [[doctr-trocr](https://github.com/kforcodeai/doctr-trocr)](https://huggingface.co/spaces/AlhitawiMohammed22/HTD_HTR)

**Comment by felixdittrich92** [comment]
Hey take a look into your `requirements.txt` python-doctr[torch] is missing ;)

**Comment by felixdittrich92** [comment]
I have pushed a relase a few minutes ago so you will get an the actual version from doctr :+1:  (version 0.7.0)
