### ISSUE TITLE
:hugs: :bug: HF demo broken 

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#1312]
### Bug description

![image](https://github.com/mindee/doctr/assets/70526046/531525c8-2563-44e7-b783-5255c91c4f62)

### Code snippet to reproduce the bug

""

### Error traceback

""

### Environment

""

### Deep Learning backend

""

**Comment by felixT2K** [comment]
@charlesmindee @odulcy-mindee That's on your side (i don't have access)🤗 
Two things about the HF demo:

1. We should automate the updates: #1090 (With each new release)
2. The demo should show the best results we can reach so i see two options:
- update the demo that you can also choose which backend should be used (TF or PT)
- switch to the backend with the "best" benchmarks (after PT trainings are done)

BTW: We can request a free gpu upgrade for the demo:
https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants

**Comment by felixdittrich92** [comment]
@odulcy-mindee You can simple copy the files from https://huggingface.co/spaces/Felix92/DocTR-demo-HF and update your demo

Only required change in README.md -> `title: DocTR Demo HF`  -> `title: docTR`  
We could also click the button and request a free update to a GPU instance from HF :sweat_smile:

**Comment by odulcy-mindee** [comment]
@felixdittrich92 Thank you very much for taking the time to fix it! :heart: 

I did the modification, now docTR HF Space is back online !
