### ISSUE TITLE
Use torch.inference_mode vs torch.no_grad for predictions

### ISSUE THREAD

**Issue by thetonus** [mindee/doctr#1316]
### 🚀 The feature

I think it would be a good idea to create a decorator (similar to the [one](https://github.com/ultralytics/ultralytics/blob/32f7c522b5a67549ac60b79b4b0b9d5aa63a6119/ultralytics/utils/torch_utils.py#L42) in Yolov8) that automatically applies the correct context manager for forward passes for code using the torch backend. 

### Motivation, pitch

Since torch>=1.9.0, there is a new context manager for inference - `torch.inference_mode`. This would allow for inferences to be faster and more memory conserved than just using `torch.no_grad`.

From [Pytorch Docs](https://pytorch.org/docs/stable/generated/torch.inference_mode.html):

> Code run under this mode gets better performance by disabling view tracking and version counter bumps. Note that unlike some other mechanisms that locally enable or disable grad, entering inference_mode also disables to [forward-mode AD](https://pytorch.org/docs/stable/autograd.html#forward-mode-ad). 

### Alternatives

None. Since Doctr is backwards compatible with older torch versions, there is no way to dynamically use `torch.inference_mode` vs `torch.no_grad`.

**Comment by thetonus** [comment]
I am more than happy to create a PR for this feature too.

**Comment by felixdittrich92** [comment]
Hi @thetonus 👋,

Thanks for the request and sure feel free to open a PR 😊
We can use the decorator directly because docTR requires torch>=1.12 so this should be fine 👍

**Comment by felixT2K** [comment]
@thetonus Part of this PR would be to add a short benchmark about inference latency and memory usage

Code to modify:
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/doctr/models/predictor/pytorch.py#L62
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/doctr/models/kie_predictor/pytorch.py#L62
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/doctr/models/recognition/predictor/pytorch.py#L43
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/doctr/models/detection/predictor/pytorch.py#L35
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/doctr/models/classification/predictor/pytorch.py#L36
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/references/classification/latency_pytorch.py#L22
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/scripts/detect_artefacts.py#L40
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/references/detection/evaluate_pytorch.py#L29
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/references/detection/latency_pytorch.py#L22
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/references/obj_detection/latency_pytorch.py#L22
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/references/recognition/evaluate_pytorch.py#L25
https://github.com/mindee/doctr/blob/7ab0ece3a4aec256bb36c311f4c6eeaa597d826b/references/recognition/latency_pytorch.py#L22
