### ISSUE TITLE
parseq and vitstr_base model on PyTorch: getting "Invalid model URL, using default initialization error" on 0.7.0

### ISSUE THREAD

**Issue by dchaplinsky** [mindee/doctr#1401]
### Bug description

I'm using the latest public release and trying to load `vitstr_base` or `parseq` models on PyTorch.

While release notes clearly states `Two new recognition models was added (ViTSTR and PARSeq) in both frameworks by @felixdittrich92 @nikokks` seems that those will be added in `0.7.1`. Any plans to release those, or should I use pip install from GitHub for now?

### Code snippet to reproduce the bug

```python
self.model = ocr_predictor(
            det_arch='db_resnet50',
            reco_arch='parseq',
            pretrained=True
        )

### Error traceback

```
Invalid model URL, using default initialization.
```

### Environment

python-doctr==0.7.0


### Deep Learning backend

```
Collecting environment information...

DocTR version: v0.7.0
TensorFlow version: N/A
PyTorch version: 2.1.1+cu121 (torchvision 0.16.1+cu121)
OpenCV version: 4.8.1
OS: Ubuntu 23.10
Python version: 3.9.18
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.147.05
cuDNN version: Could not collect
```

**Comment by dchaplinsky** [comment]
@felixdittrich92 no updates on 0.8.0 release yet?

**Comment by felixdittrich92** [comment]
Hey @dchaplinsky :wave: 

Still waiting that some runs finish :)
If https://github.com/mindee/doctr/issues/1364 is finished we will do the release
