### ISSUE TITLE
Fontconfig error！！！！

### ISSUE THREAD

**Issue by c-avan** [mindee/doctr#1423]
### Bug description

win10 系统 下搭建
程序运行后报错：
Fontconfig error: Cannot load default config file: No such file: (null)

### Code snippet to reproduce the bug

import os
import json

# Let's pick the desired backend
# os.environ['USE_TF'] = '1'
os.environ['USE_TORCH'] = '1'

import matplotlib.pyplot as plt

from doctr.io import DocumentFile
from doctr.models import ocr_predictor

# Read the file
doc = DocumentFile.from_images("receipt.jpg")
print(f"Number of pages: {len(doc)}")
result = model(doc)

### Error traceback

Fontconfig error: Cannot load default config file: No such file: (null)

### Environment

win10 + python3.8

### Deep Learning backend

略

**Comment by felixdittrich92** [comment]
Hi @c-avan Could you please post the full error traceback ?

**Comment by felixdittrich92** [comment]
Hi @c-avan 👋 
Any updates ? :)

**Comment by felixdittrich92** [comment]
Closing -> no response
