### ISSUE TITLE
Getting an error while results.show()

### ISSUE THREAD

**Issue by dinushazoomi** [mindee/doctr#1426]
### Bug description

When I try to get a OCR results from a PDF file I get the following error : 
TypeError: Document.show() missing 1 required positional argument: 'pages' 

### Code snippet to reproduce the bug

```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)
# PDF
doc = DocumentFile.from_pdf("/content/Sample_For_Assignment.pdf")
# Analyze
result = model(doc)
result.show()
```

### Error traceback

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-12-e9c5472910e5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 result.show()

TypeError: Document.show() missing 1 required positional argument: 'pages'
```

### Environment

DocTR version: v0.7.0
TensorFlow version: 2.15.0
PyTorch version: 2.1.0+cu121 (torchvision 0.16.0+cu121)
OpenCV version: 4.8.0
OS: Ubuntu 22.04.3 LTS
Python version: 3.10.12
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): No
CUDA runtime version: 12.2.140
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6

### Deep Learning backend

is_tf_available: True
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @dinushazoomi :wave: 

For version 0.7.0 (current pip) it is:

```
result.show(doc)
```

On main (next release 0.8.0)
it will be 
```
result.show()
```
The readme is already up to date with the main branch for the next release

**Comment by dinushazoomi** [comment]
Thanks @felixdittrich92
