### ISSUE TITLE
No way to load models from local

### ISSUE THREAD

**Issue by Lubhawan** [mindee/doctr#1427]
### 🚀 The feature

I have restricted access on my system. So while trying out different model, it throws ssl error. Please include a offline mode also where we can download the model to local and load it from there using model path.

### Motivation, pitch

I request this because I am working in a very restricted environment so normal model download does not work, we have to download model weights to local and load it from there.

**Comment by felixdittrich92** [comment]
You can load from local  see:
https://mindee.github.io/doctr/using_doctr/custom_models_training.html

URLs can be found in the implementation files for example:
https://github.com/mindee/doctr/blob/e5b3f462ac8defee22002a3581e0294bc49038cc/doctr/models/detection/differentiable_binarization/pytorch.py#L30

**Comment by felixdittrich92** [comment]
@Lubhawan Looks like we can close this issue ? :)

**Comment by felixdittrich92** [comment]
Seems to be solved (feel free to reopen if the issue still exists on your side) :)
