### ISSUE TITLE
Getting ValueError while using ocr predictor after loading models locally.

### ISSUE THREAD

**Issue by Lubhawan** [mindee/doctr#1431]
### Bug description

Getting ValueError while using ocr predictor after loading models locally.

### Code snippet to reproduce the bug

temp = ocr_predictor(det_arch = model, reco_arch = model_v, pretrained=False)

### Error traceback

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-c6908cc36cf2> in <module>
----> 1 temp = ocr_predictor(det_arch = model, reco_arch = model_v, pretrained=False)

~/.local/lib/python3.6/site-packages/doctr/models/zoo.py in ocr_predictor(det_arch, reco_arch, pretrained, assume_straight_pages, preserve_aspect_ratio, symmetric_pad, export_as_straight_boxes, **kwargs)
     91         symmetric_pad=symmetric_pad,
     92         export_as_straight_boxes=export_as_straight_boxes,
---> 93         **kwargs,
     94     )

~/.local/lib/python3.6/site-packages/doctr/models/zoo.py in _predictor(det_arch, reco_arch, pretrained, assume_straight_pages, preserve_aspect_ratio, symmetric_pad, det_bs, reco_bs, **kwargs)
     32         assume_straight_pages=assume_straight_pages,
     33         preserve_aspect_ratio=preserve_aspect_ratio,
---> 34         symmetric_pad=symmetric_pad,
     35     )
     36 

~/.local/lib/python3.6/site-packages/doctr/models/detection/zoo.py in detection_predictor(arch, pretrained, assume_straight_pages, **kwargs)
     73     """
     74 
---> 75     return _predictor(arch, pretrained, assume_straight_pages, **kwargs)

~/.local/lib/python3.6/site-packages/doctr/models/detection/zoo.py in _predictor(arch, pretrained, assume_straight_pages, **kwargs)
     31 
     32     if arch not in ARCHS:
---> 33         raise ValueError(f"unknown architecture '{arch}'")
     34 
     35     if arch not in ROT_ARCHS and not assume_straight_pages:

ValueError: unknown architecture 'LinkNet(
  (feat_extractor): IntermediateLayerGetter()
  (fpn): LinkNetFPN(out_chans=64)
  (classifier): <keras.engine.sequential.Sequential object at 0x7f8c620a2470>
  (postprocessor): LinkNetPostProcessor(bin_thresh=0.1, box_thresh=0.1)
)'

### Environment

/local_home/al58379/.local/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.bindings.openssl.binding import Binding
/local_home/al58379/.local/lib/python3.6/site-packages/weasyprint/document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
Collecting environment information...

DocTR version: 0.5.1
TensorFlow version: 2.6.2
PyTorch version: 1.1.0.dev20190422 (torchvision 0.2.2)
OpenCV version: 4.5.5
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Python version: 3.6.8
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: Could not collect
cuDNN version: /usr/lib64/libcudnn.so.7.5.1

### Deep Learning backend

is_tf_available: True
is_torch_available: True

**Comment by felixT2K** [comment]
Hi @Lubhawan 👋🏼,

You use a really old version (0.5.1 current is 0.7.0) - loading from local was added in 0.6.0 i suggest to update to the latest published version

Best regards,
Felix

**Comment by Lubhawan** [comment]
Thank you

**Comment by felixdittrich92** [comment]
@Lubhawan has it solved your problem ? :)

**Comment by felixdittrich92** [comment]
Seems to be solved (feel free to reopen if the issue is still not solved on your side) :)
