### ISSUE TITLE
[documents] Check for input PDF with PyMuPDF when it's source content

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#144]
So far, we have used the content reading feature of PyMuPDF. When a source PDF is read, the library actually extracts all the localization and text information from the document. Two options are then available:
- skipping the model inference and use this
- combining it with the model inference to improve our predictions

**Comment by charlesmindee** [comment]
I think we should skip inference in that case, why would we loose time to have worst performances ?
