### ISSUE TITLE
The local demo doesn't work with the latest version of streamlit. Please specify the version of streamlit in docs or update demo code.

### ISSUE THREAD

**Issue by dchaplinsky** [mindee/doctr#1446]
### Bug description

The code snippet below returns the traceback below on the most recent streamlit (1.29.0 at the moment of publishing).

Downgrading streamlit to 1.25.0 fixes the problem

### Code snippet to reproduce the bug

```bash
pip install streamlit==1.29.0
USE_TORCH=1 streamlit run ../../doctr/demo/app.py
```

### Error traceback

```
streamlit.errors.DeprecationError:
════════════════════════════════════════════════
deprecation.showfileUploaderEncoding IS NO LONGER SUPPORTED.

deprecation.showfileUploaderEncoding has been deprecated and will be removed in a future version.

Please update <user defined>.
```

### Environment

Doctr master
Streamlit 1.29.0
Python 3.11

### Deep Learning backend

is_tf_available: False
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @dchaplinsky :wave:,

Thanks for reporting this we will apply a fix soon or if you have already feel free to create a PR :hugs:

**Comment by dchaplinsky** [comment]
Didn't dig it to the core issue, just fixed by downgrading streamlit, which was enough for my purposes.

**Comment by felixdittrich92** [comment]
I think removing the following line will fix it:
https://github.com/mindee/doctr/blob/f5445efa91c6ae72d04eaa7c13af7980ee1c8018/demo/app.py#L53

Not tested yet
