### ISSUE TITLE
How to use just the recognition model with a custom object detection crop?

### ISSUE THREAD

**Issue by ajkdrag** [mindee/doctr#1464]
### Discussed in https://github.com/mindee/doctr/discussions/1463

<div type='discussions-op-text'>

<sup>Originally posted by **ajkdrag** February 12, 2024</sup>
I am doing object detection with a different framework, which gives me the bboxes for few text regions i am interested in. When I run just the recognition_predictor of DocTR, the output is gibberish. Am I missing something here? When I run ocr_predictor on the entire original image, the detection and recognition results seem to look fine. </div>

**Comment by felixdittrich92** [comment]
Hi @ajkdrag :wave:,

Please use the discussion section for such questions :)

**Comment by ajkdrag** [comment]
Hi, looks like i was trying to use the Parseq model, but since the pretrained URL isn't available yet, so it was giving me gibbering. 
I can close this issue, but a little help on these questions:
1. If I ignore Parseq, which is the current best recog model for texts, provided by DocTR?
2. If I want to use Parseq with release 0.7, how can I do so? Do I have to use the main branch and install from there?
Thanks!

**Comment by felixdittrich92** [comment]
1. with 0.7.0 it is `crnn_vgg16_bn` or `crnn_mobilenet_v3_large`
2. correct you would need to install from the main branch (we will do the 0.8.0 release soon) :)
