### ISSUE TITLE
https://pipedream.com suppport

### ISSUE THREAD

**Issue by marcelocecin** [mindee/doctr#1466]
### 🚀 The feature

Hello, please consider adapting the way to initialize the module, indicating in which folder to save the necessary files that are installed

### Motivation, pitch

The error says it’s failing to find a file or directory. Perhaps this package downloads files to a specific directory during install?
It may need to be configured to download files to /tmp instead, because that’s the only directory that’s writeable in your workflow.

### Additional context

https://pipedream.com/docs/code/python/import-mappings/#using-magic-comments
<img width="995" alt="" src="https://github.com/mindee/doctr/assets/2955762/57da3927-a992-4d74-b641-9fd086db0923">

**Comment by felixdittrich92** [comment]
Hey @marcelocecin :wave:,

Correct, but you can specify the cache folder by your own. See:
https://mindee.github.io/doctr/using_doctr/running_on_aws.html

Best regards,
Felix

**Comment by marcelocecin** [comment]
thanks @felixdittrich92 !

**Comment by marcelocecin** [comment]
now I'm facing the Import Error
`libGL.so.1: cannot open shared object file: No such file or directory`

I asked for help in the pipedream community and they guided me like this:
`You might want to report that to the maintainers of the project. There might be an undocumented environment variable you’ll need to set in order to exclude that dependency.`

**Comment by felixdittrich92** [comment]
You need to install 
`apt-get install libgl1-mesa-dev` for opencv :)

**Comment by marcelocecin** [comment]
On the Pipedream platform, it is not possible to install this dependency individually. Would it be possible to include this dependency in the package?

**Comment by felixdittrich92** [comment]
Unfortunately no. 
However, this is a frequently needed dependency, so you should ask the support team :) 
Do you have a chance to specify the docker image that should be used under the hood ?

**Comment by ctrlaltdylan** [comment]
Pierce from Pipedream here 👋 

Unfortunately at this time we don't support custom docker containers, but we know this is a product gap.

Another else reading this thread, please feel free to comment and/or subscribe to this issue: https://github.com/PipedreamHQ/pipedream/issues/798

That will close as soon as we have this feature support in one way or another.

**Comment by felixdittrich92** [comment]
Hi @ctrlaltdylan :wave:,

Thanks for the response :+1: 
@marcelocecin I think in this case we can close the issue.
Our docker images are available at: https://github.com/mindee/doctr/pkgs/container/doctr (including CUDA support)

**Comment by marcelocecin** [comment]
Thank you Felix
<img width="1054" alt="" src="https://github.com/mindee/doctr/assets/2955762/3d8ce527-7393-4356-8e0c-74b7ffa1baa2">
