### ISSUE TITLE
I can't load the db_resnet50_rotation model from the main branch

### ISSUE THREAD

**Issue by fsimonAramis** [mindee/doctr#1474]
### Bug description

When I try to install python-doctr from Pypi or from the main branch of the repo, I can't use the db_resnet50_rotation model.
I have the error : WARNING:root:Invalid model URL, using default initialization.
Or I also have the error that it is impossible to use this model with this architecture. 

To use this model I need to checkout to commit id : e645ead 
And install the package from this commit.

How can I use this model without having to checkout to this specific commit ? 

### Code snippet to reproduce the bug

```
import os
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
 
list_file= os.listdir('img_tmp')

model = ocr_predictor(
    det_arch="db_resnet50_rotation",
    reco_arch="parseq",
    pretrained=True,
    det_bs=8,
    reco_bs=1024,
    assume_straight_pages=False,
    straighten_pages=True,
    detect_orientation=True,
)  

for i in list_file:
    image_file=DocumentFile.from_images(tmp/{i}') 
    result = model(image_file)
    json_res = result.export()
    print(json_res["pages"][0]["orientation"]["value"])
```

### Error traceback

```
WARNING:root:Invalid model URL, using default initialization.
```

### Environment

doctr.__version__ = 0.8.0a0

### Deep Learning backend

>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: False
>>> print(f"is_torch_available: {is_torch_available()}")
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @fsimonAramis 👋,
This model is replaced by `db_resnet50` which works now also on rotated documents :)
