### ISSUE TITLE
ModuleNotFoundError: No module named 'doctr.io'; 'doctr' is not a package

### ISSUE THREAD

**Issue by harbhajan21** [mindee/doctr#1484]
### Bug description

I'm using doctr from last 7 months. But today when did I try to run the new program using doctr package with tensforflow, I'm getting below error:

ModuleNotFoundError: No module named 'doctr.io'; 'doctr' is not a package

Even I installed all packages after uninstalling it. but it's not working.

### Code snippet to reproduce the bug

"""
import streamlit as st
from PIL import Image
from doctr.io import DocumentFile
from doctr.models import ocr_predictor

# Load the OCR model
model = ocr_predictor(pretrained=True)

st.title('OCR with Doctr and Streamlit')

uploaded_file = st.file_uploader("Choose an image file", type=["jpg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image.', use_column_width=True)
    
    # Convert the image to a Doctr document
    doc = DocumentFile.from_images([image])

    # Perform OCR on the document
    result = model(doc)

    # Extract the text from the OCR result
    text = ' '.join(block.text for page in result.pages for block in page.blocks)
    
    st.write(text)

"""

### Error traceback

File "c:\users\abc\appdata\local\programs\python\python39\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\Users\abc\Desktop\Tool\doctr.py", line 3, in <module>
    from doctr.io import DocumentFile
File "C:\Users\abc\Desktop\Tool\doctr.py", line 3, in <module>
    from doctr.io import DocumentFile

### Environment

NA

### Deep Learning backend

NA

**Comment by felixdittrich92** [comment]
Hi @harbhajan21 reaname your `doctr.py` file :)

**Comment by felixdittrich92** [comment]
@harbhajan21 any updates ? :)

**Comment by harbhajan21** [comment]
yes, I have fixed the issues. Thanks for your response.
