### ISSUE TITLE
Extend the REST API endpoints so that they can me parameterized

### ISSUE THREAD

**Issue by eudoxos** [mindee/doctr#1537]
### 🚀 The feature

Currently, there are 4 endpoints (detection, kie, ocr, recognition) which only take the image file as parameter. Ideally, they would be extended to support the same basic options as the streamlit app (detection model, recognition model, threshold, straight pages assumption), and they also could return the same JSON as the streamlit app does (including confidence for detected elements)

### Motivation, pitch

I would like to use doctr deployed in docker container, and the endpoints don't have enough flexibility.

### Alternatives

Installing doctr in the same docker container as the main (compiled) app and call external python process for the detection, without REST API. It will work, but there is less separation, independent upgrades will be more difficult, which is especially relevant due to to the size of doctr dependencies.

**Comment by felixdittrich92** [comment]
Hi @eudoxos :wave:,

Good idea i have already started to update the api a bit in https://github.com/mindee/doctr/pull/1522
We could in a follow up PR integrate the rest of the `ocr_predictor` options :)

**Comment by felixdittrich92** [comment]
done :)
