### ISSUE TITLE
Cannot run library, issues with gobject-2.0-0

### ISSUE THREAD

**Issue by dvalletj** [mindee/doctr#1545]
### Bug description

I'm on Mac OS 13.5.1, running Python 3.9 and I cannot run the library in my python script, been stuck on this for a few days, have tried installing gobject-2.0-0 with no success:

`OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/python3.9/site-packages/../../gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/bin/../lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache). Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
`

```
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/python3.9/site-packages/../../gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/bin/../lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache). Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

### Error traceback

```from doctr.io import DocumentFile```

### Environment

--2024-04-10 15:23:27--  https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10644 (10K) [text/plain]
Saving to: 'collect_env.py'

collect_env.py   100%[=======>]  10.39K  --.-KB/s    in 0s      

2024-04-10 15:23:27 (39.2 MB/s) - 'collect_env.py' saved [10644/10644]

### Deep Learning backend

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

Traceback (most recent call last):
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/depen.py", line 1, in <module>
    from doctr.file_utils import is_tf_available, is_torch_available
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/doctr/__init__.py", line 1, in <module>
    from . import io, models, datasets, transforms, utils
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/doctr/io/__init__.py", line 2, in <module>
    from .html import *
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/doctr/io/html.py", line 8, in <module>
    from weasyprint import HTML
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/weasyprint/text/ffi.py", line 428, in <module>
    gobject = _dlopen(
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/weasyprint/text/ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/dv/Desktop/Internal/tjn-lease-abstract/.venv/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dv/opt/anaconda3/lib/gobject-2.0-0' (no such file), '/Users/dv/opt/anaconda3/bin/../lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by dvalletj** [comment]
@felixdittrich92, I have tried that and same results unfortunately. Importing the library on any file gives the error.

**Comment by felixdittrich92** [comment]
@odulcy-mindee @frgfm 

I've been observing for over a year now that `weasyprint` keeps causing problems for Windows and Mac users. 
Maybe we should manage it as an optional dependency because it's only used for `DocumentFile.from_url` atm and i think most people use `.from_images` or `.from_pdf`

**Comment by frgfm** [comment]
@felixdittrich92 I fully agree, we should make that an optional dependencies in the next release! Perhaps we could have an extra called "plugins"?

**Comment by felixdittrich92** [comment]
@frgfm i would personally prefer something like an ImportError
```
try:
    import weasyprint
except ImportError:
    raise .. ("To use the `.from_url` functinality you need to install `weasyprint` <Link to weasyprint Install docs>")
```
instead of an extra dependency block
We could do the same with matplotlib 

For testing the dev dependencies will still keep all optional dependencies

Wdyt ? :)

**Comment by felixdittrich92** [comment]
Also related to #1052

**Comment by felixdittrich92** [comment]
@frgfm btw i think we could also move to opencv-python-headless (conda version is available) because we don't need the gui part from opencv-python to reduce the package size

**Comment by wesamalnabki** [comment]
I was facing a similar issue and solved by installed weasyprint using conda:

`conda install weasyprint`

**Comment by felixdittrich92** [comment]
Will be optional with the next release #1551  :)

**Comment by dhea1323** [comment]
I got a same error on Windows 11
