### ISSUE TITLE
Unable to extract text in both directions

### ISSUE THREAD

**Issue by nk-alex** [mindee/doctr#1547]
### Bug description

Given an image with text in both directions (horizontal and vertical), I'm not able to extract text

Sample image:

![tUiSO](https://github.com/mindee/doctr/assets/101177816/9e128212-798c-4f5a-8280-992d9e4bbac5)

### Code snippet to reproduce the bug

`ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True)`
- Returning " SMAL COMPANY M B GFEEL"

`ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True, assume_straight_pages=False)`
- "You are trying to use a model trained on straight pages while not assuming your pages are straight. If you have only straight documents, don't pass assume_straight_pages=False, otherwise you should use one of these archs:['db_resnet50_rotation']"

`ocr_predictor(det_arch='db_resnet50_rotation', reco_arch='crnn_vgg16_bn', pretrained=True, assume_straight_pages=False)`
- Returns "UST NE'RE FOR"

```
ocr_predictor(
    det_arch="fast_base",
    reco_arch="parseq",
    pretrained=True,
    det_bs=8,
    reco_bs=1024,
    assume_straight_pages=False,
    straighten_pages=False,
    detect_orientation=True,
)
```
- Returns unknown architecture 'fast_base'

### Error traceback

-

### Environment

Python 3.9.18
python-doctr 0.7.0

### Deep Learning backend

is_tf_available: False
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @nk-alex :wave:,

Could you try one of the `fast` models please (only available on main branch atm) these works much better with rotated texts

**Comment by nk-alex** [comment]
Thank you for the quick response @felixdittrich92.

I tried the following:

`pip install -U git+https://github.com/mindee/doctr.git@main`

**pip list is showing now python-doctr 0.9.0a0**

```
ocr_predictor(
    det_arch="fast_base",
    reco_arch="parseq",
    pretrained=True,
    det_bs=8,
    reco_bs=1024,
    assume_straight_pages=False,
    straighten_pages=False,
    detect_orientation=True,
)

```

I see is trying to download from https://doctr-static.mindee.com/models?id=v0.8.1/fast_base-688a8b34.pt&src=0 which returns "HTTP Error 308: Permanent Redirect"

**Comment by felixdittrich92** [comment]
Mh .. but it is available: https://github.com/mindee/doctr/releases/download/v0.8.1/fast_base-688a8b34.pt

CC @odulcy-mindee

**Comment by felixdittrich92** [comment]
Could you please retry and report back if it's still not working ? 
Unfortunately i can not reproduce this behaviour

**Comment by odulcy-mindee** [comment]
Hello @nk-alex, any update ?

**Comment by nk-alex** [comment]
Sorry for the delay. Now it  successfully downloads.

This is my result in this case:

```
ocr_predictor(
    det_arch="fast_base",
    reco_arch="parseq",
    pretrained=True,
    det_bs=8,
    reco_bs=1024,
    assume_straight_pages=False,
    straighten_pages=False,
    detect_orientation=True,
)
```

 - Returns: "A - JUST I I  - - N C WE'RE ( - Ju I I - - I   - PA - - NV - A FOR - I - - 44 STRIVING"

**Comment by felixdittrich92** [comment]
You are right all models have problems with the large text parts:

![Screenshot from 2024-04-15 16-15-16](https://github.com/mindee/doctr/assets/23098070/326d2f52-570c-4faf-976e-0adb2379a11f)


So the vertical text is detected and recognized correctly but the horizontal large text isn't.

**Comment by odulcy-mindee** [comment]
> I think that's a problem from the dataset we use for pretraining because it contains mostly commonly seen documents/receipts @odulcy-mindee correct me if it contains other data 😅

Yeah, indeed, we don't have such image in our dataset

**Comment by felixdittrich92** [comment]
Hey @nk-alex :wave:,

yeah i see looks like the detection model has some problems with the vertical text in your example. 
Normally on the samples i have used for testing it works pretty well. 
Could you test it on some real samples you want to process and check if it works ?
But yeah of course we will further optimize the models step by step :)

**Comment by nk-alex** [comment]
Hi @felixdittrich92 with the ocr_predictor configuration specified above, on real samples, I get some of the vertical words but not most of them. Is there any other ocr_predictor configuration with better results for this use case?

Something like this is what I get in most cases:

Sample1             |  Sample2
:-------------------------:|:-------------------------:
![Captura de pantalla 2024-04-17 090901](https://github.com/mindee/doctr/assets/101177816/adb1c051-2f50-41a6-9bf4-488c9c55b680) |  ![Captura de pantalla 2024-04-17 091521](https://github.com/mindee/doctr/assets/101177816/6874dc9d-dda0-4798-b724-e821c3e366f8)

**Comment by wesamalnabki** [comment]
I'm facing the same problem here. The vertical text is not detected at all.

```
from doctr.models import ocr_predictor
ocr_model = ocr_predictor(det_arch = "db_resnet50",# "linknet_resnet50",
                        reco_arch = "crnn_vgg16_bn",
                        pretrained = True,
                        pretrained_backbone = True,
                        assume_straight_pages = False, 
                        preserve_aspect_ratio = True, 
                        symmetric_pad = True, 
                        export_as_straight_boxes = True, 
                        detect_orientation = False, 
                        straighten_pages = True, 
                        detect_language = False)

# Modify the binarization threshold and the box threshold
ocr_model.det_predictor.model.postprocessor.bin_thresh = 0.3
ocr_model.det_predictor.model.postprocessor.box_thresh = 0.2
```


![vert_w](https://github.com/mindee/doctr/assets/6717881/b1a5bd20-e0f9-4f9a-9164-3e4aaf12f9a9)

**Comment by felixdittrich92** [comment]
Moved to #1604
