### ISSUE TITLE
Support for detecting special symbols like bullet points, check boxes, etc.

### ISSUE THREAD

**Issue by parthpatel002** [mindee/doctr#1570]
### 🚀 The feature

Currently, all text detection models in docTR do not seem to identify special characters like bullet points, check boxes, etc. (likely because the training data is so) - attaching sample outputs (clipped screenshots of document pages). We should be able to detect these symbols to increase detection coverage to all text present on a page.
Bullet points:
<img width="762" alt="image" src="https://github.com/mindee/doctr/assets/30209886/406d9481-18d2-46f6-8a82-0c44eef488dd">
Checkboxes:
<img width="748" alt="image" src="https://github.com/mindee/doctr/assets/30209886/7de1777c-d0e4-42f8-9247-6121736c94bd">

### Motivation, pitch

Symbols like bullet points, checkboxes, etc. form an integral part of the text content of many types of documents in general and OCR should be able to detect as well as recognize these symbols to increase coverage to all text present on the page.

**Comment by felixdittrich92** [comment]
Hi @parthpatel002 :wave:,

with bullet points i agree (but as you already mentioned there are no such samples in the pretraining dataset).
About the check boxes i think this would be more a topic for document layout parsing :)

But we have on the roadmap to pretrain on https://huggingface.co/datasets/pixparse/pdfa-eng-wds

**Comment by felixdittrich92** [comment]
Added to #1604
