### ISSUE TITLE
Margin in Crops

### ISSUE THREAD

**Issue by ArsalanYounus007** [mindee/doctr#1582]
### Bug description

Hello,

I hope you are having a good day. I am getting some problem with db_resnet_50 (TF). The output Bbox contains a lot of margin and overlaps with the boxes around it.
![image](https://github.com/mindee/doctr/assets/34642875/1ac92ecc-faa0-42ce-ba7a-ba396d89e9b5)

I was able to fix the problem by increasing the bin_thresh to 0.5 - 0.6 and applying further post processing turning it into this

![image](https://github.com/mindee/doctr/assets/34642875/a0ef702c-0cc8-41c5-a71f-1c0453fb2f68)

That solves the Bbox overlapping issue for me but started another problem, Now words are missing.
![missing_words](https://github.com/mindee/doctr/assets/34642875/be890042-3692-4ca0-8ffc-7e00395da077)

This I was able to fix by splitting image (original images are big 2550 width x 3300 height) into 2 by finding the most empty location in the middle of image. OCRing that make the detection better. But still miss some words occassionally.

What would you recommend?? Aside from training my own detection model 😆 (I will do it later)

### Code snippet to reproduce the bug

```
from doctr.models import ocr_predictor
model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn',assume_straight_pages=True,pretrained=True)
model.det_predictor.model.postprocessor.bin_thresh = 0.4
model.det_predictor.model.postprocessor.box_thresh = 0.4
json_output = model([single_img_doc])
```

### Error traceback

NA

### Environment

Conda ENV
Python3.10
Windows 11

### Deep Learning backend

![image](https://github.com/mindee/doctr/assets/34642875/e7090a08-b3bf-4749-9fbc-fb02234d4a4d)

**Comment by felixdittrich92** [comment]
Hey @ArsalanYounus007 👋
A short suggestion:
If possible take the main branch and try `fast_base` or `db_resnet50` (pytorch) :)

**Comment by ArsalanYounus007** [comment]
I have already tried pytorch db_resnet50, It's better but still misses words.
I will try fast_base with pytorch and see the results

**Comment by felixdittrich92** [comment]
> I have already tried pytorch db_resnet50, It's better but still misses words. I will try fast_base with pytorch and see the results

Keep in mind `fast_base` is only available at main branch atm :)

**Comment by ArsalanYounus007** [comment]
Yep, It's better at detecting words
However, I am back at the overlapping Bboxes from left (if it's not the first word) and right.
