### ISSUE TITLE
Save the OCRed PDF

### ISSUE THREAD

**Issue by micos7** [mindee/doctr#1595]
### 🚀 The feature

I`d like to save the pdf after OCR

### Motivation, pitch

-

### Alternatives

I tried something like  this but exceptions all over 

       `doc = DocumentFile.from_pdf(pdf_content)
        # Perform OCR using doctr
        model = ocr_predictor(pretrained=True)
        result = model(doc)

        # Extract text from the OCR result
        text = ""
        for page in result.pages:
            for block in page.blocks:
                for line in block.lines:
                    for word in line.words:
                        text += word.value + " "

        # Save the OCR result back to the original file path
        with open(body.url, 'w') as pdf_file:
            pdf_file.write(text)`

### Additional context
Thanks for  your work.

_No response_

**Comment by felixdittrich92** [comment]
Hi @micos7 : 👋
What you want to create is a PDF/A File (PDF with text layer).
Please take a look at https://mindee.com/blog/create-ocrized-pdfs-in-2-steps :)

**Comment by felixdittrich92** [comment]
Any updates @micos7 ? :)
