### ISSUE TITLE
Possible Issue with the current License

### ISSUE THREAD

**Issue by gvalvano** [mindee/doctr#1730]
### 🚀 The feature

I see the library has been released following the Apache-2.0 license. However, it relies on GPLv2+ license dependencies. 
Can we remove such dependencies?

### Motivation, pitch

To really have Apache 2.0, we must ensure that the library is actually usable with that license!

In particular, pip-installing `python-doctr` will also install:
- [pyphen (0.16.0)](https://pypi.org/project/pyphen/): ['GNU General Public License v2 or later (GPLv2+)', 'GNU Lesser General Public License v2 or later (LGPLv2+)', 'Mozilla Public License 1.1 (MPL 1.1)'] --> installed by `weasyprint`
- [Unidecode (1.3.8)](https://pypi.org/project/Unidecode/): ['GNU General Public License v2 or later (GPLv2+)']

### Additional context

```
weasyprint==61.2
    # via python-doctr
pyphen==0.16.0
    # via weasyprint
pyphen==0.16.0
    # via weasyprint


2 packages.
    pyphen (0.16.0): ['GNU General Public License v2 or later (GPLv2+)', 'GNU Lesser General Public License v2 or later (LGPLv2+)', 'Mozilla Public License 1.1 (MPL 1.1)']
      dependency:
          pyphen
    Unidecode (1.3.8): ['GNU General Public License v2 or later (GPLv2+)']
      dependency:
          Unidecode
```

**Comment by felixdittrich92** [comment]
Hi @gvalvano :wave: 

`weasyprint` is an optional dependency and will be only installed by the `html` extensions for example: 
```
pip install "python-doctr[torch,html]"
```

:)  ref.: https://mindee.github.io/doctr/getting_started/installing.html

**Comment by gvalvano** [comment]
Nice! :D thanks for your answer! This solved my issue!

Do you think we can add this to the installation guide, somewhere? So it is easier to find it for future users

**Comment by felixdittrich92** [comment]
Hi @gvalvano 🤗
Yes sure would you like to open a PR ?
We could add it here: https://github.com/mindee/doctr/blob/main/docs/source/getting_started/installing.rst
