### ISSUE TITLE
Inconsistency between `detection_predictor` and `ocr_predictor().det_predictor` resize parameters

### ISSUE THREAD

**Issue by cmoscardi** [mindee/doctr#1764]
### Bug description

Hi,
I noticed that by default, the `doctr.models.ocr_predictor` initializer passes `preserve_aspect_ratio=True` and `symmetric_pad=True` to the `Resize` step of the preprocessor. 

However, `doctr.models.detection_predictor` does not pass any parameter, and the `Resize` class defaults to `preserve_aspect_ratio=False` and `symmetric_pad=False`. This leads to inconsistencies in (default) preprocessing depending on how one initializes their detection predictor.

**Possible Solutions**
1. Change default of `ocr_predictor` 
2. Include `symmetric_pad` and `preserve_aspect_ratio` as explicit kwargs in `detection_predictor` with default set to `True`
3. Change the defaults of the `Resize` class to align with the defaults of `ocr_predictor`

I suspect you have trained your baseline models with these preprocessing parameters set to `True` , so I'll assume #1 is out. While I'm new to the package, my gut tells me solution #3 has a greater risk of creating inconsistencies elsewhere. Plus, as a user, solution #2 makes the `detection_predictor()` API align more closely with the `ocr_predictor()` API.

Hope this helps! Since I'm looking at this at the moment, I'll create a PR implementing solution #2 in the next few mins and feel free to do as you wish with it.

PS I discovered this while working on this project, which has been going very well! Thanks for a great package. https://www.christianmoscardi.com/blog/2024/10/03/digitizing-us-statistical-abstracts.html

### Code snippet to reproduce the bug

```python
from doctr.models import ocr_predictor, detection_predictor

det_predictor_from_scratch = detection_predictor()
det_predictor_from_ocr = ocr_predictor().det_predictor

# notice the preserve_aspect_ratio=True and symmetric_pad=True in description of the resize step
print(det_predictor_from_ocr)

# description of the resize step does not include the preserve_aspect_ratio and symmetric_pad
print(det_predictor_from_scratch)
```

### Error traceback

The negative outcome is deteriorated model performance due to different preprocessing than what model was trained on.

### Environment

```
(ocr-math) christianmoscardi@Christians-MacBook-Pro ~ % python collect_env.py 
Collecting environment information...

DocTR version: 0.9.0a0
TensorFlow version: 2.15.1
PyTorch version: 2.1.2.post3 (torchvision 0.16.1)
OpenCV version: 4.9.0
OS: Mac OSX 15.0.1
Python version: 3.11.0
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
```

### Deep Learning backend

```
is_tf_available: True
is_torch_available: True
```

**Comment by felixdittrich92** [comment]
Hi @cmoscardi 👋,

I have read your blog post it's really amazing to read - good job 👍 
I would like to add a reference in the documentation to such community "controbution" how does this sound to you ? :)

CC @odulcy-mindee wdyt ?

About your PR i will have a look (hopefully tomorrow) 🤗
