### ISSUE TITLE
ImportError: cannot import name 'DocumentFile' from 'doctr.documents' 

### ISSUE THREAD

**Issue by othmanechentouf** [mindee/doctr#213]
Whenever I try to execute the same code presented in the main page, I get this error : "ImportError: cannot import name 'DocumentFile' from 'doctr.documents' (/Users/Aksol/miniconda3/lib/python3.8/site-packages/doctr/documents/__init__.py)".
I can't find a solution around it, I tried cloning the repo in Google Colab and I still get the same error.
Has anyone came across the same problem and had a solution around it ?
Thank you

**Comment by fg-mindee** [comment]
Hi @othmanechentouf :wave: 

Thanks for the issue! Would you mind either specifying how you installed doctr? :pray: Or run this
```
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
and report the results back here 

Most likely, looking at the error message you mentioned, you installed it from pypi, which is the last release. The readme on the main branch refers to the codebase as is, which keeps evolving between each release. If so, you can run the following to solve your problem:
```
git clone https://github.com/mindee/doctr.git
pip install -e doctr/.
```
It will install the main branch version! Let me know if that helped!

**Comment by othmanechentouf** [comment]
Thank you for your fast answer @fg-mindee 💯  , this is why I got from running the first commands : 
Collecting environment information...

DocTR version: N/A
TensorFlow version: 2.4.1
OpenCV version: 4.2.0
OS: Mac OSX 11.0.1
Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

The error has gone now, but now I get this error : "
ModuleNotFoundError: No module named 'doctr.version'"

Hope you can help me out with it too.

Thank you in advance.

**Comment by othmanechentouf** [comment]
Thank you for your fast answer @fg-mindee 💯 , this is why I got from running the first commands :
Collecting environment information...
DocTR version: N/A
TensorFlow version: 2.4.1
OpenCV version: 4.2.0
OS: Mac OSX 11.0.1
Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
The error has gone now, but now I get this error : "
ModuleNotFoundError: No module named 'doctr.version'"
Hope you can help me out with it too.
Thank you in advance.

**Comment by fg-mindee** [comment]
That's strange. Let's investigate this:

1. Can you uninstall all existing versions of the package and reinstall?
For this, run the following comands and say yes if asked to confirm
```
pip uninstall python-doctr
pip uninstall doctr
```
Then navigate where you cloned the repo:
```
cd <path/to/doctr>
pip install -e . --upgrade
```

2. Try importing doctr
```python
import doctr
```
If you get any errors, let me know

3. Print the version
```python
import doctr
print(doctr.__version__)
```
Let me know what gets printed if this runs successfully :pray:

**Comment by othmanechentouf** [comment]
Import doctr works fine with no errors but I still get this error when trying to print the version :

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-88d1aa650148> in <module>
      1 import doctr
----> 2 print(doctr.__version__)

AttributeError: module 'doctr' has no attribute '__version__'

**Comment by fg-mindee** [comment]
Oh two things then:
- if it's a notebook, once you've reinstalled doctr, you need to "restart kernel"
- once it's done, try again the command: "from doctr.documents import DocumentFile" it should work

**Comment by othmanechentouf** [comment]
It is working perfectly now, Thank you for your help!!
