### ISSUE TITLE
Demo app error when analyzing my first document

### ISSUE THREAD

**Issue by Morluche** [mindee/doctr#216]
## 🐛 Bug

I tried to analyze a PNG and a PDF, got the same error. I try to change the model, didn't change anything.

## To Reproduce

1. Upload a PNG
2. Click on analyze document

```
KeyError: 0
Traceback:
File "/Users/thibautmorla/opt/anaconda3/lib/python3.8/site-packages/streamlit/script_runner.py", line 337, in _run_script
    exec(code, module.__dict__)
File "/Users/thibautmorla/Downloads/doctr/demo/app.py", line 93, in <module>
    main()
File "/Users/thibautmorla/Downloads/doctr/demo/app.py", line 77, in main
    seg_map = predictor.det_predictor.model(processed_batches[0])[0]
```

## Additional context

First image upload

**Comment by fg-mindee** [comment]
Hi @Morluche !
Thanks for reporting this, would you mind sharing the doc or image that you used so that we can reproduce the error please ? :pray:

**Comment by Morluche** [comment]
<img width="396" alt="Capture d’écran 2021-03-01 à 11 21 43" src="https://user-images.githubusercontent.com/66415445/116097331-570c3100-a6aa-11eb-82b1-90606bcb748a.png">
[dropcontact_invoice_Azq8WZSSg3AUMHCT (1).pdf](https://github.com/mindee/doctr/files/6377755/dropcontact_invoice_Azq8WZSSg3AUMHCT.1.pdf)
