### ISSUE TITLE
[transforms] Failing unittests for transformation

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#256]
The following CI job is failing: https://github.com/mindee/doctr/pull/254/checks?check_run_id=2565047900
The reason behind that might either be an edge case or because of the modifications from #249

**Comment by fg-mindee** [comment]
Recent occurrence of the bug: https://github.com/mindee/doctr/runs/2618450417

**Comment by fg-mindee** [comment]
I think we have to rewrite the unittests for several transformations because of #249

**Comment by charlesmindee** [comment]
Is this still an issue @fg-mindee ?

**Comment by fg-mindee** [comment]
Yes, I think we have to completely rewrite the unittests for those transformation with randomness. Since our unittests use random tensors, the issue doesn't occurr every single time, but this is still an ongoing issue

**Comment by fg-mindee** [comment]
Another occurence: https://github.com/mindee/doctr/pull/277/checks?check_run_id=2639277079
