### ISSUE TITLE
[models] Stop changing aspect ratio for detection task

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#275]
It seems that modifying aspect ratio when resizing to 1024 x 1024 is highly harmful for the OCR for non-squared docs such as cheques, IBAN, cards, etc...

We need to pad images on the smaller side instead.

**Comment by fg-mindee** [comment]
Agreed, we have to investigate the impact on already trained models (since they do not benefit from the same resizing method) before starting a PR though

**Comment by charlesmindee** [comment]
After performing evaluation of our baseline model (trained with a non-aspect-ratio-preserving dataset) with our test datasets preserving the aspect ratio of images for the detection task, it seems that it is improving slightly the detection results for the IDS dataset:

without aspect ratio: `Text Detection - Recall: 70.04%, Precision: 72.17%, Mean IoU: 58.67%`
with aspect ratio: `Text Detection - Recall: 69.60%, Precision: 73.13%, Mean IoU: 60.60%`

We can see that Mean IOU is significantly higher, and precision is better too, which means that if we retrain our models preserving the aspect ratio of images this should improve performances even more. For other datasets such as CORD, the performances are slightly worse if we keep the aspect ratio, but I believe this is due to overfitting because we trained our models on squared deformed images, but training the detector with padded images should improve the results.

**Comment by charlesmindee** [comment]
This has been fixed in #766, since this PR one has only to pass `preserve_aspect_ratio=True` to the `ocr_predictor` (or the `detection_predictor`) to preserve the aspect ratio of the image when resizing. We didn't train our models with that option for the moment, but we just have to pass this argument to `T.resize` in the training scripts to begin to train this way.
