### ISSUE TITLE
Duplicate words in OCR result

### ISSUE THREAD

**Issue by jonathanMindee** [mindee/doctr#330]
## 🐛 Bug

Running the sample code:
```
from doctr.documents import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)
# PDF
doc = DocumentFile.from_images(["table.png"])
# Analyze
result = model(doc)

result.show(doc)
```

I get this result:

![image](https://user-images.githubusercontent.com/41388086/123510227-9808cd80-d67a-11eb-84d5-2290a9c086c1.png)

Everything looks fine but there is some overlap between different words. The mouse is pointing to the word "Header4" and there is another word with the content "4". In that case I'm not able to reconstruct properly the table header as there is either an extra "4".

## To Reproduce

1. download this image

<img width="1219" alt="table" src="https://user-images.githubusercontent.com/41388086/123510338-2c733000-d67b-11eb-817d-a2d335c3238b.png">

2. Run the following code
```
from doctr.documents import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)
# PDF
doc = DocumentFile.from_images(["table.png"])
# Analyze
result = model(doc)

result.show(doc)
```

**Comment by jonathanMindee** [comment]
I think using some overlap detection postprocessing it's possible to filter out those duplicates.

**Comment by fg-mindee** [comment]
Thanks for reporting this!

I'm not sure which way would be the best, but here are some ideas to handle this:
- **Batch post-processing**: NMS to perform with a looser threshold.
- **Manual post-processing**: estimate candidate overlaps with a box IoU. For pairs where there is a text overlap as well, we perform a manual NMS (taking the one with the longest string while having the confidence above a given threshold). The probable issue would be that the predicted resulting string will wrongly not include the blank space.
- **Training-based**: we add blank space as part of the vocab in the recognition and use NMS.

The first option being natively implemented in most modern DL frameworks, it might be a suitable option to try first

**Comment by charlesmindee** [comment]
As a matter of fact, we do want to suppress very small boxes included in other ones, so I suggest the following:
- performing NMS with a very high threshold to filter boxes covered by other ones (avoid repetitions without loosing information).
- merging boxes with a consistent overlapping but with a lower IOU, to keep all the information we need.

This overlapping seems to be mostly frequent with underscores, so I think it is a good approximation to merge boxes in that case (technically, it is the same word). What do you think @fg-mindee ?

![ex1 png](https://user-images.githubusercontent.com/70526046/123619336-5d816b00-d809-11eb-8798-17d954207284.png)

**Comment by fg-mindee** [comment]
@charlesmindee Thanks for the suggestion!
However when I suggested an NMS, I thinking about the iterative merging implementation of it
So I fully agree that pure filtering won't be enough. As you mentioned, we might need to use another metric than IoU :+1:

**Comment by fg-mindee** [comment]
Coming back to this issue, I suggest the following:
- Investigate the heatmap of the text detection module to assess whether this comes from the segmentation or box conversion part (I'm especially interested in the overlapping localization candidates shown on the issue description image)
- discuss options to handle the situation depending on our findings 
- as shown earlier, NMS isn't really the best option here since we're talking about small IoU overlaps. So if we tweak this NMS, that will start merging words that are correctly separated by a blank space

But let's not leave this issue unaddressed :smiley:

**Comment by felixT2K** [comment]
@frgfm @charlesmindee @odulcy-mindee 

Seems to be solved with `preserve_aspect_ratio=True`.
(Both TF and PT are identically)
I have tested some personal documents and keeping the aspect ratio was always the better choice ... Should we use it by default wdyt ?

```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True, preserve_aspect_ratio=True)
# PDF
doc = DocumentFile.from_images(["/home/felix/Desktop/table.png"])
# Analyze
result = model(doc)

result.show(doc)
```
![Screenshot from 2023-07-25 08-15-10](https://github.com/mindee/doctr/assets/125863421/27a4686a-5ac5-4f58-b33f-cf3f66717500)

**Comment by charlesmindee** [comment]
Hi @felixdittrich92, thanks for the suggestion, I think we can change the default behaviour since it is quite natural to preserve the aspect ratio by default. Moreover, it will make the predictions robuster to cropping.
