### ISSUE TITLE
[datasets] size issue when drawing with default font

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#417]
When using the default font to draw on 32 x 32 images, we have a size issue:
![default](https://user-images.githubusercontent.com/70526046/129878926-3cb1bbd2-78f9-4c91-aa2a-5d541b04660c.png)
This is due to the following: PIL uses a default fixed size of 10 for the default font, and we can't change it. The only way to deal with it is to draw on a 10 x 10 image and interpolate afterwards to 32 x 32, which is pretty ugly.

**Comment by fg-mindee** [comment]
I think it's highly related to #416 OS-specific default fonts

However it's true that from a given font to another, characters won't necessarily have the same height for the same font size. We might need to automatically resize those :thinking:

**Comment by charlesmindee** [comment]
closed by #418

**Comment by fg-mindee** [comment]
Perhaps that on top of default font, we should have a default font size? (to make sure this doesn't yield really small characters for some font families)
