### ISSUE TITLE
[support] Add support of TensorFlowJS

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#431]
Since DocTR fully supports TensorFlow, being able to run DocTR features in the browser using TFJS would be a neat improvement!

**Comment by charlesmindee** [comment]
After investigating, I managed to convert the db_resnet50 (without all numpy & opencv post processing) and the crnn_vgg16_bn (without ctc decoding) to JSON models for tfjs web serving, and I successfully performed browser-based predictions for both recognition and recognition task:

- For the recognition task, it is easy to implement a ctc decoder in javascript, thus we can perform inference on text box images, and return predicted words in the browser.

- For the detection task, we can easily return the raw output of the JSON model for a document (the probability map, segmentation result), but it seems far more harder to perform the whole post processing pipeline to extract all boxes from this raw map in javascript.

To conclude, to perform end to end inference (combining detection + recognition task) on documents we should find a way to deal with the whole post processing pipeline between the detection and recognition tasks in JavaScript .

**Comment by charlesmindee** [comment]
Some updates:
- We managed to bridge the 2 tasks through a post processing with opencv js. 
- The mobilenet_v3 of doctr is not running on tfjs because of FusedConv/FusedBatchNorms, so we used a mobilenet_v2 backbone from the keras hub. 
- The db_resnet50 + crnn_vgg16_bn is running on RTX 20../30..with tfjs but on RTX 10.. the resnet is too heavy this is why we switched to a mobilenet and we are working with inputs of 512 x 512 (to make it lighter).

**Comment by fg-mindee** [comment]
Quick update everyone: 
- we have a functioning demo running with TFJS!
- still needs a few front-end improvements, the code will be shared soon :)

**Comment by charlesmindee** [comment]
I guess this is not an issue anymore since we released this repo:
https://github.com/mindee/doctr-tfjs-demo

What do you think @fg-mindee ?

**Comment by faizankarim** [comment]
@charlesmindee @fg-mindee can you share how you converted crnn_vgg16_bn to tfjs format?
i want to train it on english and spanish vocab and run that on tfjs.
Thanks
