### ISSUE TITLE
Vocabs

### ISSUE THREAD

**Issue by fmobrj** [mindee/doctr#436]
Hello!

I am amazed by the incredible results you achieved with doctr. Congrats. I have been experimenting with it and it is mind blowing.

I see the library work with some character sets / vocabs. It would be great if the Latin set would include some very common portuguese characters not included in the latin set, as ã, õ, Ã, Õ. They are very common in portuguese text and end up degrading the result for the language. In general, all other characters are present.   

Bets regards,
Fabio.

**Comment by fg-mindee** [comment]
What do you say @fmobrj ? :) 
Fancy opening a PR? (if you need some help, we'd be happy to provide some assistance)

**Comment by fmobrj** [comment]
Ok. I will try. I am a noob to github. If I need some assistance, I contact you.

**Comment by fg-mindee** [comment]
Sounds good @fmobrj :+1: 
Try following the steps I mentioned above, that should hopefully help you in the process

**Comment by fmobrj** [comment]
When running "pip install -e doctr/.[tf]" after clonning the repository, I get the following error:

`(doctr_dev) (base) jamazzon@jamazzon-MS-7A94:/media/hdd3tb/data$ pip install -e doctr/.[tf]
Obtaining file:///media/hdd3tb/data/doctr
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/media/hdd3tb/data/doctr/setup.py", line 32
        print(f"Building wheel {package_name}-{version}")
                                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /media/hdd3tb/data/doctr/
`

**Comment by fg-mindee** [comment]
Mmmh it looks like your Python version don't support f-strings. Would you be running Python 2 by any chance?

If you do have Python 3.6+, try using `pip3 install -e doctr/.[tf]` instead. If not, it's better to install Python3 since support for Python2 has ended and all modern Python tools have switched to Python3

**Comment by fmobrj** [comment]
I could get over it. Using python -m pip ...

Now, I have a doubt. I installed everything and ran "git checkout -b portuguese-vocab"

Where are the files of the new branch located? The same directory where the repository was cloned?

**Comment by fmobrj** [comment]
I created the PR. Hope everything is correct.

**Comment by fg-mindee** [comment]
Thanks a lot @fmobrj :pray: I just reviewed the PR!
(To do some modifications, go to the repo location on your laptop and go through step5-7 to update the PR with your modifications)

**Comment by fmobrj** [comment]
Hi, @fg-mindee. You are welcome. As I said, I am kind of a noob with github. Should I take some additional action or is everything ok?

**Comment by fg-mindee** [comment]
There are just a few things to modify, cf my comment here: https://github.com/mindee/doctr/pull/464#pullrequestreview-752843039
Let me know if you run into any trouble!
