### ISSUE TITLE
rotate_abs_boxes return unexpected output

### ISSUE THREAD

**Issue by mouhannadali** [mindee/doctr#455]
## 🐛 Bug

rotate_abs_boxes return unexpected output

## To Reproduce

1. giving img_shape =(20, 20, 3)
2. boxes = np.array([[0, 0, 5, 10]])
3. angle=90

call:
```
from doctr.utils import geometry

r_boxes = geometry.rotate_abs_boxes(boxes, angle, img_shape)

```
## Expected behavior

I was expecting to have the following output:
`array([[ 0. , 15.,  20. , 10. , 90. ]])
`
the current output is:
`array([[ 5. , 17.5,  5. , 10. , 90. ]])
`
did I misunderstand what the method should do?

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - DocTR Version (e.g., 0.1.0):
 - TensorFlow Version (e.g., 2.5.0):
 - PyTorch & torchvision versions (e.g., 1.8.0 & 0.9.0):
 - OpenCV Version (e.g., 4.5.1):
 - OS (e.g., Linux):
 - How you installed DocTR (`conda`, `pip`, source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by charlesmindee** [comment]
Hi @mouhannadali, 
The rotate_absolute_box fonction returns a rotated box: [x_center, y_center, w, h, angle] where (x_center, y_center) is the box center and w, h are the (inchanged) width and height of the rectangle. The rotation is performed around the page center. Does this answer your question ? 
Have a nice day!

**Comment by charlesmindee** [comment]
Hi @mouhannadali, 
The rotate_absolute_box fonction returns a rotated box: [x_center, y_center, w, h, angle] where (x_center, y_center) is the box center and w, h are the (inchanged) width and height of the rectangle. The rotation is performed around the page center. Does this answer your question ? 
Have a nice day!

**Comment by charlesmindee** [comment]
Hi @mouhannadali, 
The rotate_absolute_box fonction returns a rotated box: [x_center, y_center, w, h, angle] where (x_center, y_center) is the box center and w, h are the (inchanged) width and height of the rectangle. The rotation is performed around the page center. Does this answer your question ? 
Have a nice day!

**Comment by mouhannadali** [comment]
Hi @charlesmindee  thanks for the replay. I am confused a little bit. if I have the following bbox in an image:
![Untitled](https://user-images.githubusercontent.com/17967903/131970058-ca19e30d-f4c2-4950-959d-65b0d72dd8aa.png)
and rotate is around the image center (90d)  then should be like this:
![Untitled](https://user-images.githubusercontent.com/17967903/131970212-4ceb8001-0211-431b-9621-8705acc8b2c2.png)
where the w and h have switched or?

**Comment by fg-mindee** [comment]
Hello @mouhannadali :wave: 

Apologies for the confusion, I think we need to detail a few things in the documentation. @charlesmindee is correct, the output is indeed (x_center, y_center, w, h, angle). However, what you need to consider is the following:
- the center coordinates are as you described
- the (w, h) represents the width and height **before the rotation**

The reason behind this is that for intermediate rotation (say 30°), rotating the box doesn't yield a straight bounding box that covers only the area of the initial object. So we do perform an actual rotation of the bounding box, and to avoid information degradation, we provide all the information. So in your case, performing a 90° will effectively, as you mentioned, provide values that look like w & h are switched.

Another difference your illustration seems to point: our rotation is counter-clockwise :) 

To be able to correctly plot this, you can use `cv2` which includes utils for rotated bounding boxes with the same coordinate format!

I hope this helps :)

**Comment by mouhannadali** [comment]
thanks, that helps a lot, and also thanks for the supper doctr tool :)
