### ISSUE TITLE
Import error synthetize_page func in streamlit demo script

### ISSUE THREAD

**Issue by Nicolas-Schuhl** [mindee/doctr#476]
## 🐛 Bug

Import bug while running the streamlit demo script

## To Reproduce

1. Install the current package version 
2. Run streamlit demo/app.py

Error message : ImportError: cannot import name 'synthetize_page' from 'doctr.utils.visualization' (/home/ubuntu/repos/mindee/doctr/doctr/utils/visualization.py)

## Correction 

Try to import "synthetize_page" [from](https://github.com/mindee/doctr/blob/cfc329f8b21cd7d8c08d5c9190c53bd77a3149c4/doctr/utils/visualization.py#L19) whereas it should be "synthesize_page" [here](https://github.com/mindee/doctr/blob/cfc329f8b21cd7d8c08d5c9190c53bd77a3149c4/demo/app.py#L21) . It's probably a typo. It works after renaming.

**Comment by charlesmindee** [comment]
Hi @Nicolas-Schuhl, thanks for spotting that!

**Comment by fg-mindee** [comment]
@Nicolas-Schuhl that should be fixed by #477 on the `main` branch now :+1:
