### ISSUE TITLE
Rotation issue when extracting crops if rotated_bbox=False

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#482]
If rotated_bbox=False, we however rotate the whole bitmap if a significant angle is detected, thus we need to rotate the original image as well before extracting crops otherwise we crop the wrong parts of the images

Reference in the predictor (both tf & pt):
https://github.com/mindee/doctr/blob/ab7d483ab09218d5f88e976d9d3dbbd6263de9ef/doctr/models/predictor/tensorflow.py#L65
https://github.com/mindee/doctr/blob/ab7d483ab09218d5f88e976d9d3dbbd6263de9ef/doctr/models/predictor/pytorch.py#L71

**Comment by fg-mindee** [comment]
Things to take care of:
- [x] Clean flags and handle the default case where we assume that the page is straight and all its text elements (#551)
- [ ] Refactors that rotation scheme in predictors

**Comment by charlesmindee** [comment]
Closed by #641 (no page rotation anymore)
