### ISSUE TITLE
OSError: no library called "cairo" was found

### ISSUE THREAD

**Issue by sriprad** [mindee/doctr#505]
## 🐛 Bug

Hi Team,
Please find the code i tried to run and it gave me the following error

## To Reproduce

```python
from doctr.documents import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)
# PDF
doc = DocumentFile.from_pdf("/Invoice extraction_PDFS_Document understanding/F1906-00027.pdf").as_images()
# Analyze
result = model(doc)
```

yields the following output

```
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

**Comment by fg-mindee** [comment]
Hi @sriprad,

Would you mind running the environment collection script?
```
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
python collect_env.py
```

My best guess is that you might on MacOS or a similar OS and need to install some prerequisites. There are some additional details in the documentation: https://mindee.github.io/doctr/installing.html#prerequisites

Let me know if that doesn't help!

**Comment by sriprad** [comment]
Hi @fg-mindee ,
thank you for sharing this. I will try this out and get back to you. So far no success. I am on Windows machine.

**Comment by sriprad** [comment]
Hi @fg-mindee 
I could fix it . thank you
