### ISSUE TITLE
Adding hocr output to generate Pdf/A

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#512]
Hi, 
adding the option to get the output in hocr format or directly as pdf/A (searchable text layer) would be great :) 
Any chance to receive this currently ?
Best regards

**Comment by charlesmindee** [comment]
Hi @felixdittrich92, 

Thanks for asking, it was not on the road map but since you are asking we may consider adding this export option, if I understand well it consists in putting the output this way: (?)

`...
<p class='ocr_par' lang='deu' title="bbox930">
  <span class='ocr_line' title="bbox 348 797 1482 838; baseline -0.009 -6">
    <span class='ocrx_word' title='bbox 348 805 402 832; x_wconf 93'>Die</span> 
    <span class='ocrx_word' title='bbox 421 804 697 832; x_wconf 90'>Darlehenssumme</span> 
    <span class='ocrx_word' title='bbox 717 803 755 831; x_wconf 96'>ist</span> 
    <span class='ocrx_word' title='bbox 773 803 802 831; x_wconf 96'>in</span> 
    <span class='ocrx_word' title='bbox 821 803 917 830; x_wconf 96'>ihrem</span> 
    <span class='ocrx_word' title='bbox 935 799 1180 838; x_wconf 95'>ursprünglichen</span> 
    <span class='ocrx_word' title='bbox 1199 797 1343 832; x_wconf 95'>Umfange</span> 
    <span class='ocrx_word' title='bbox 1362 805 1399 823; x_wconf 95'>zu</span> 
    <span class='ocrx_word' title='bbox 1417 x_wconf 96'>ver-</span> 
  </span>
  ...`

If so, I think it is easy to map our `Page` output containing `blocks`,` lines` and `words` to such a format.

Have a nice day!

**Comment by felixdittrich92** [comment]
@charlesmindee 
yes this would be great :+1: after this generating a Pdf/A is a short step
in a way like this example:
```
from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.units import inch
from xml.etree.ElementTree import ElementTree
import Image, re, sys

class HocrConverter():
    """
    A class for converting documents to/from the hOCR format.

    For details of the hOCR format, see:

        http://docs.google.com/View?docid=dfxcv4vc_67g844kf

    See also:

        http://code.google.com/p/hocr-tools/

    Basic usage:

    Create a PDF from an hOCR file and an image:

        hocr = HocrConverter("path/to/hOCR/file")
        hocr.to_pdf("path/to/image/file", "path/to/output/file")

    """
    def __init__(self, hocrFileName = None):
        self.hocr = None
        self.xmlns = ''
        self.boxPattern = re.compile('bbox((\s+\d+){4})')
        if hocrFileName is not None:
            self.parse_hocr(hocrFileName)

    def __str__(self):
        """
        Return the textual content of the HTML body
        """
        if self.hocr is None:
            return ''
        body =  self.hocr.find(".//%sbody"%(self.xmlns))
        if body:
            return self._get_element_text(body).encode('utf-8') # XML gives unicode
        else:
            return ''

    def _get_element_text(self, element):
        """
        Return the textual content of the element and its children
        """
        text = ''
        if element.text is not None:
            text = text + element.text
        for child in element.getchildren():
            text = text + self._get_element_text(child)
        if element.tail is not None:
            text = text + element.tail
        return text

    def element_coordinates(self, element):
        """
        Returns a tuple containing the coordinates of the bounding box around
        an element
        """
        out = (0,0,0,0)
        if 'title' in element.attrib:
            matches = self.boxPattern.search(element.attrib['title'])
        if matches:
            coords = matches.group(1).split()
            out = (int(coords[0]),int(coords[1]),int(coords[2]),int(coords[3]))
        return out

    def parse_hocr(self, hocrFileName):
        """
        Reads an XML/XHTML file into an ElementTree object
        """
        self.hocr = ElementTree()
        self.hocr.parse(hocrFileName)

        # if the hOCR file has a namespace, ElementTree requires its use to find elements
        matches = re.match('({.*})html', self.hocr.getroot().tag)
        if matches:
            self.xmlns = matches.group(1)
        else:
            self.xmlns = ''

    def to_pdf(self, imageFileName, outFileName, fontname="Courier", fontsize=8):
        """
        Creates a PDF file with an image superimposed on top of the text.

        Text is positioned according to the bounding box of the lines in
        the hOCR file.

        The image need not be identical to the image used to create the hOCR file.
        It can be scaled, have a lower resolution, different color mode, etc.
        """
        if self.hocr is None:
        # warn that no text will be embedded in the output PDF
            print("Warning: No hOCR file specified. PDF will be image-only.")

            im = Image.open(imageFileName)
            imwidthpx, imheightpx = im.size
        if 'dpi' in im.info:
            width = float(im.size[0])/im.info['dpi'][0]
            height = float(im.size[1])/im.info['dpi'][1]
        else:
        # we have to make a reasonable guess
        # set to None for now and try again using info from hOCR file
            width = height = None


        ocr_dpi = (300, 300) # a default, in case we can't find it

        # get dimensions of the OCR, which may not match the image
        if self.hocr is not None:
            for div in self.hocr.findall(".//%sdiv"%(self.xmlns)):
                if div.attrib['class'] == 'ocr_page':
                    coords = self.element_coordinates(div)
                    ocrwidth = coords[2]-coords[0]
                    ocrheight = coords[3]-coords[1]
                if width is None:
                    # no dpi info with the image
                    # assume OCR was done at 300 dpi
                    width = ocrwidth/300
                    height = ocrheight/300
                ocr_dpi = (ocrwidth/width, ocrheight/height)
                break # there shouldn't be more than one, and if there is, we don't want it

        if width is None:
            # no dpi info with the image, and no help from the hOCR file either
            # this will probably end up looking awful, so issue a warning
            print("Warning: DPI unavailable for image %s. Assuming 96 DPI."%(imageFileName))
            width = float(im.size[0])/96
            height = float(im.size[1])/96

        # create the PDF file
        pdf = Canvas(outFileName, pagesize=(width*inch, height*inch), pageCompression=1) # page size in points (1/72 in.)

        # put the image on the page, scaled to fill the page
        pdf.drawInlineImage(im, 0, 0, width=width*inch, height=height*inch)

        if self.hocr is not None:
            for line in self.hocr.findall(".//%sspan"%(self.xmlns)):
                if line.attrib['class'] == 'ocr_line':
                    coords = self.element_coordinates(line)
                    text = pdf.beginText()
                    text.setFont(fontname, fontsize)
                    text.setTextRenderMode(3) # invisible

                    # set cursor to bottom left corner of line bbox (adjust for dpi)
                    text.setTextOrigin((float(coords[0])/ocr_dpi[0])*inch, (height*inch)-(float(coords[3])/ocr_dpi[1])*inch)

                    # scale the width of the text to fill the width of the line's bbox
                    text.setHorizScale((((float(coords[2])/ocr_dpi[0]*inch)-(float(coords[0])/ocr_dpi[0]*inch))/pdf.stringWidth(line.text.rstrip(), fontname, fontsize))*100)

                    # write the text to the page
                    text.textLine(line.text.rstrip())
                    pdf.drawText(text)

        # finish up the page and save it
        pdf.showPage()
        pdf.save()

    def to_text(self, outFileName):
        """
        Writes the textual content of the hOCR body to a file.
        """
        f = open(outFileName, "w")
        f.write(self.__str__())
        f.close()

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print('Usage: python HocrConverter.py inputHocrFile inputImageFile outputPdfFile')
        sys.exit(1)
    hocr = HocrConverter(sys.argv[1])
    hocr.to_pdf(sys.argv[2], sys.argv[3])
```

**Comment by fg-mindee** [comment]
Hi @felixdittrich92,

That sounds like an interesting result export!
If you feel like it, perhaps you could open a PR to integrate that? :)

**Comment by felixdittrich92** [comment]
@fg-mindee 
yes i will do hopefully next week if i found a bit time in addition to a 40 hour work week and family ^^
Can you add the hocr output in that time?

Example:
`hocr_format = pytesseract.image_to_pdf_or_hocr(image, extension='hocr')`

I will also talk to my manager on monday if i can get time to contribute under work to this project ( i build currently intern a OCR engine but would be much usefuller to contribute my stuff at this place and then use the product result intern)
So everyone benefits from it :) Let's see

**Comment by felixdittrich92** [comment]
@fg-mindee get the go and will start tomorrow :)

**Comment by fg-mindee** [comment]
@felixdittrich92 my bad, I've had limited availability :sweat_smile: 

I suggest doing the following (one PR for each to avoid getting ahead of ourselves):
- [ ] implement a function that uses the `Document` out of the current predictor and reorders the `Block`, `Line` and `Word` (or the results of both blocks). This PR should only implement the `oraganize_elements` function, this should not change the default behaviour.
- [ ] Integrate this with the `.render` method (this will change the default behaviour)

We'll see how we move forward after this :+1:

**Comment by fg-mindee** [comment]
For reference, this is also linked to #511

**Comment by felixdittrich92** [comment]
@fg-mindee 
I have now started to integrate a solution to sort bboxes (left to right works but i have to investigate time tomorrow for the top to bottom sorting part) infront of the line / block organizing ! can we connect with Slack for short discussions ?

**Comment by fg-mindee** [comment]
Actually we do but it's really basic over here: https://github.com/mindee/doctr/blob/main/doctr/models/builder.py#L40
It definitely needs some improvement :)

I'll check how to best move forward for these discussions indeed, let me get back to you :ok_hand:

**Comment by felixdittrich92** [comment]
@fg-mindee 
i try currently to solve this but its a bit tricky to found a solution only on top of bounding box coordinates 
what i currently try is to compute the middle_centroids for each box and then to sort this and boxes

so the reason is if the boxes are not correctly sorted i do not know a way to build lines or blocks:

for lines i compute the distance beetween the actual box coordinate right upper and the following left upper if there is no big value change (threshold computation dependent on image sizes) it will be concatenated to a line else break and new line starts

for blocks i think i can then use the coords from lines to check the line distances

**Comment by fg-mindee** [comment]
Well, even if we sort the boxes, we're projecting 2D information into a 1-D plane. Considering 2 column pages exist, bounding box sorting is only a naive approach.

Perhaps some sort of clustering using the centroids to identify blocks, and then for each block, we can sort the boxes? It's gonna be experimental either way :man_shrugging:

**Comment by felixdittrich92** [comment]
@charlesmindee 
@fg-mindee 
Any idea about that? I had read it now in several issues the sorting of the boxes is really a big problem and affects all output formats (export, render, ..) Would be great to find a solution before further features come


best regards and have a nice weekend :)

**Comment by fg-mindee** [comment]
Sounds good @felixdittrich92, thanks again :pray:

**Comment by felixdittrich92** [comment]
@fg-mindee 
yes then i think it would be good to provide/implement 2 methods in `DocumentBuilder` 

1. export_hocr : returns the plain XML (so parse blocks/lines/words into XML-format-later) for each page
2. export_pdfa (needs output from export_hocr): returns a pdfa file as base64 ? or save to a given path + name ? and for each page or merged ? or make it flexible ? ^^

What do you think ?

**Comment by fg-mindee** [comment]
> can we connect with Slack for short discussions ? After this the line part will work and block is near

My bad, I just realized I forgot to let you know! You can join the [Slack](https://join.slack.com/t/mindee-community/shared_invite/zt-uzgmljfl-MotFVfH~IdEZxjp~0zldww) for Mindee community where you'll find a `#doctr` channel! See you there :smile:
