### ISSUE TITLE
Imperfect merging of strings from split boxes

### ISSUE THREAD

**Issue by Param-Raval** [mindee/doctr#521]
Hello!

Thank you for an amazing implementation! The new release (4.0.0) has some great new work, however I'm facing an issue with one of the new features.

The feature of "dynamic crop splitting for wide inputs to recognition models" (#465) incorrectly merges the recognition results of the new crops.

### To Reproduce
```
im_path = "path/to/image_with_long_text.png"
single_img_doc = DocumentFile.from_images(im_path)
model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True)
result = model(single_img_doc)
result.show(single_img_doc)
```

### The Issue

The word image having text "0000-XX-12-0001234" is split into two crops whose respective recognition results are: `('0000-XX-12-', '-12-0001234')`. However, after merging, the final result is `0000-XX-12-12-0001234`. This problem is recurring for several similar words, so I'm guessing the approach to merging the strings with Levenshtein distance is buggy. Unfortunately, I can't provide the images for these cases for privacy reasons.

Hoping for some help on this. Thank you!

**Comment by charlesmindee** [comment]
Hi @Param-Raval, 

Thanks for the feedback. Could you please attach one (or more) images concerned by the issue so that I can debug that on my side ?

Thanks ! :pray: 

Have a nice day!

**Comment by fg-mindee** [comment]
Yes, on my side, I wasn't able to reproduce this: I tried to create a simple image with the same text (cf. below)
![faulty_merging](https://user-images.githubusercontent.com/76527547/135838534-d95e0d11-b11f-4825-ba82-aa150c82d3ba.png)

And the following snippet:
```python
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
model = ocr_predictor(pretrained=True)
doc = DocumentFile.from_images("/home/fg/Downloads/faulty_merging.png")
print(model(doc))
```

yields:
```
Page(
  dimensions=(960, 640)
  (blocks): [Block(
    (lines): [Line(
      (words): [Word(value='0000-XX-12-00001234', confidence=0.95)]
    )]
    (artefacts): []
  )]
)
```

@Param-Raval if you could give a simple image to reproduce this, that would be helpful :pray:

**Comment by Param-Raval** [comment]
Hello!

Thank you for your response. Here is an image that leads to this issue.
![claim_long](https://user-images.githubusercontent.com/47474201/136004861-1107a90d-6ec6-43bc-ad6b-b78bbc571e78.png)

The output for this sequence is `0000-XX-1-25-9-9-19-000-21358` and the respective output of the split boxes are: `('0000-XX-', 'X-1-25-9-', '-9-19-000-', '000-21358')` 

I also noticed that the split/merge feature fails in this way for sequences with a '-' (hyphen), especially when the '-' character is right before/after a split point (just like in the above example, and the example I gave when raising the issue).

Thank you for your help!

**Comment by fg-mindee** [comment]
@Param-Raval so we will have to investigate whether this does not impact overall performances negatively, but for your use case, you can tune the split strategy as follows:

```python
from doctr.models import ocr_predictor
from doctr.io import DocumentFile
doc = DocumentFile.from_images('/home/fg/Downloads/troubles.png')
predictor = ocr_predictor(pretrained=True)
# Change the target aspect ratio of final crops (default is 4)
predictor.reco_predictor.target_ar = 6
print(predictor(doc))
```
now yields:
```
Document(
  (pages): [Page(
    dimensions=(960, 640)
    (blocks): [Block(
      (lines): [Line(
        (words): [Word(value='0000-XX-1-25-9-19-000-21358', confidence=0.49)]
      )]
      (artefacts): []
    )]
  )]
)
```

On our end, we'll have to check how far we can push the aspect ratio without degrading text recognition performances!
Let me know if that helped :smile:

**Comment by Param-Raval** [comment]
Thanks a lot! I'll try it and get back if needed. Good luck :pray:
