### ISSUE TITLE
OSError: no library called "cairo"/cairo2 was found in Windiws

### ISSUE THREAD

**Issue by yourabhi** [mindee/doctr#529]
## To Reproduce

1.
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - DocTR Version (e.g., 0.1.0):
 - TensorFlow Version (e.g., 2.5.0):
 - PyTorch & torchvision versions (e.g., 1.8.0 & 0.9.0):
 - OpenCV Version (e.g., 4.5.1):
 - OS (e.g., Linux):
 - How you installed DocTR (`conda`, `pip`, source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by yourabhi** [comment]
OSError: no library called "cairo/cairo 2" was found in windows

**Comment by fg-mindee** [comment]
Any update @yourabhi? We cannot do much with so little information unfortunately :sweat_smile:

**Comment by Tharunkumar01** [comment]
I got the same error. I am a windows 10 user. 
**My Error code:** 
`OSError 
Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19732/2728866201.py in <module>
----> 1 from doctr.io import DocumentFile
      2 from doctr.models import ocr_predictor
      3 
      4 model = ocr_predictor(pretrained=True)
      5 # PDF

c:\users\tharun\src\python-doctr\doctr\__init__.py in <module>
----> 1 from . import datasets, io, models, transforms, utils
      2 from .file_utils import is_tf_available, is_torch_available
      3 from .version import __version__  # noqa: F401

c:\users\tharun\src\python-doctr\doctr\datasets\__init__.py in <module>
      1 from doctr.file_utils import is_tf_available
      2 
----> 3 from .classification import *
      4 from .cord import *
      5 from .detection import *

c:\users\tharun\src\python-doctr\doctr\datasets\classification\__init__.py in <module>
      2 
      3 if is_tf_available():
----> 4     from .tensorflow import *
      5 elif is_torch_available():
      6     from .pytorch import *  # type: ignore[misc]

c:\users\tharun\src\python-doctr\doctr\datasets\classification\tensorflow.py in <module>
      6 import tensorflow as tf
      7 
----> 8 from .base import _CharacterGenerator
      9 
     10 __all__ = ['CharacterGenerator']

c:\users\tharun\src\python-doctr\doctr\datasets\classification\base.py in <module>
      8 from PIL import Image, ImageDraw
      9 
---> 10 from doctr.io.image import tensor_from_pil
     11 from doctr.utils.fonts import get_font
     12 

c:\users\tharun\src\python-doctr\doctr\io\__init__.py in <module>
      1 from .elements import *
----> 2 from .html import *
      3 from .image import *
      4 from .pdf import *
      5 from .reader import *

c:\users\tharun\src\python-doctr\doctr\io\html.py in <module>
      6 from typing import Any
      7 
----> 8 from weasyprint import HTML
      9 
     10 __all__ = ['read_html']

~\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\__init__.py in <module>
    467 
    468 # Work around circular imports.
--> 469 from .css import preprocess_stylesheet  # noqa isort:skip
    470 from .html import (  # noqa isort:skip
    471     HTML5_UA_COUNTER_STYLE, HTML5_UA_STYLESHEET, HTML5_PH_STYLESHEET,

~\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\css\__init__.py in <module>
     25 from ..logger import LOGGER, PROGRESS_LOGGER
     26 from ..urls import URLFetchingError, get_url_attribute, url_join
---> 27 from . import computed_values, counters, media_queries
     28 from .properties import INHERITED, INITIAL_NOT_COMPUTED, INITIAL_VALUES
     29 from .utils import get_url, remove_whitespace

~\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\css\computed_values.py in <module>
     13 from tinycss2.color3 import parse_color
     14 
---> 15 from .. import text
     16 from ..logger import LOGGER
     17 from ..urls import get_link_attribute

~\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\text.py in <module>
      9 import re
     10 
---> 11 import cairocffi as cairo
     12 import cffi
     13 import pyphen

~\AppData\Local\Programs\Python\Python39\lib\site-packages\cairocffi\__init__.py in <module>
     46 
     47 
---> 48 cairo = dlopen(
     49     ffi, ('cairo-2', 'cairo', 'libcairo-2'),
     50     ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))

~\AppData\Local\Programs\Python\Python39\lib\site-packages\cairocffi\__init__.py in dlopen(ffi, library_names, filenames)
     43     error_message = '\n'.join(  # pragma: no cover
     44         str(exception) for exception in exceptions)
---> 45     raise OSError(error_message)  # pragma: no cover
     46 
     47 

OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e`

**This is how I installed the package:** 
`!pip install -e git+https://github.com/mindee/doctr.git#egg=python-doctr[torch]`

**Comment by fg-mindee** [comment]
Hi @Tharunkumar01 :wave:

Thanks for providing the traceback and the command! Have you installed the [prerequisites](https://mindee.github.io/doctr/latest/installing.html#prerequisites) before attempting the pip install? (MacOS & Windows don't ship with the same preinstalled elements as Linux distributions)

**Comment by Tharunkumar01** [comment]
Thank you @fg-mindee. It worked after installing GTK.

**Comment by fg-mindee** [comment]
No problem, happy to help :+1:

**Comment by anindya-dey** [comment]
Hi, I am facing a similar issue. When I scrolled through the entire thread, I stumbled on the [prerequisites](https://mindee.github.io/doctr/latest/installing.html#prerequisites) link, but it is dead (404 Not Found). Can someone please share an updated prerequisites link?

**Comment by anindya-dey** [comment]
OK, as mentioned in one of the comments, I too solved it after install the latest GTK release from [here](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases).
