### ISSUE TITLE
set resolve_lines and resolve_blocks to True

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#547]
## 🐛 Bug

As discussed in #512 it needs an improvement for the `sort_boxes ` to set the `resolve_lines` and `resolve_blocks` in `builder.py `to True as default

In fact of this the `.render()` and `.export_as_xml()` results are not correct 

## To Reproduce

1. test with any document image which has multible text blocks/lines or where the document is slightly crooked in the picture, for example photographed by a mobile phone

## Expected behavior

Correct sorted boxes left-right / top-bottom that the lines and blocks can be resolved correctly

## Environment

-DocTR version: 0.4.1a0
-TensorFlow version: N/A
-PyTorch version: 1.9.1 (torchvision 0.10.1)
-OpenCV version: 4.4.0
-OS: Ubuntu 20.04.3 LTS
-Python version: 3.8
-Is CUDA available (TensorFlow): N/A
-Is CUDA available (PyTorch): No
-CUDA runtime version: Could not collect
-GPU models and configuration: Could not collect
-Nvidia driver version: Could not collect
-cuDNN version: Could not collect

**Comment by zalakbhalani** [comment]
> Hi @felixdittrich92,
> 
> I am going to time the line/block resolution algorithms to see if it doesn't slow down (too much) the inference speed to add them by default 😄. If it is quick enough, we can resolve lines and blocks by default, otherwise we will add an option in the OCRPredictor to be able to control these args of the DocumentBuilder at the highest level.

It will be very helpful to add these arguments to OCRpredictor. Can I work on that?

**Comment by fg-mindee** [comment]
Hi @zalakbhalani :wave: 

Thanks for offering to apply the modifications! Since I had a bit of time, I took the liberty of opening #809 that will take care of that :+1:
