### ISSUE TITLE
Adding hOCR parser example for xml output

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#562]
@fg-mindee 
Where to add the example ? 
And in which format ? python script or jupyter notebook ?

Example code:
```
#
# Lets take a look how to generate a PDF/A document with the doctr output.
#

import re
import numpy as np
from math import atan, cos, sin
from typing import Optional, Tuple, Dict
from xml.etree import ElementTree as ET
from xml.etree.ElementTree import Element

from reportlab.lib.colors import black
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.utils import ImageReader
from PIL import Image

# First define the hOCR (xml) parser


class HocrParser():

    def __init__(self):
        self.box_pattern = re.compile(r'bbox((\s+\d+){4})')
        self.baseline_pattern = re.compile(r'baseline((\s+[\d\.\-]+){2})')

    def _element_coordinates(self, element: Element) -> Dict:
        """
        Returns a tuple containing the coordinates of the bounding box around
        an element
        """
        out = out = {'x1': 0, 'y1': 0, 'x2': 0, 'y2': 0}
        if 'title' in element.attrib:
            matches = self.box_pattern.search(element.attrib['title'])
            if matches:
                coords = matches.group(1).split()
                out = {'x1': int(coords[0]), 'y1': int(coords[1]), 'x2': int(coords[2]), 'y2': int(coords[3])}
        return out

    def _get_baseline(self, element: Element) -> Tuple[float, float]:
        """
        Returns a tuple containing the baseline slope and intercept.
        """
        if 'title' in element.attrib:
            matches = self.baseline_pattern.search(element.attrib['title']).group(1).split()
            if matches:
                return float(matches[0]), float(matches[1])
        return (0.0, 0.0)

    def _pt_from_pixel(self, pxl: Dict, dpi: int) -> Dict:
        """
        Returns the quantity in PDF units (pt) given quantity in pixels
        """
        pt = [(c / dpi * inch) for c in pxl.values()]
        return {'x1': pt[0], 'y1': pt[1], 'x2': pt[2], 'y2': pt[3]}

    def _get_element_text(self, element: Element) -> str:
        """
        Return the textual content of the element and its children
        """
        text = ''
        if element.text is not None:
            text += element.text
        for child in element:
            text += self._get_element_text(child)
        if element.tail is not None:
            text += element.tail
        return text

    def export_pdfa(self,
                    out_filename: str,
                    hocr: ET.ElementTree,
                    image: Optional[np.ndarray] = None,
                    fontname: str = "Times-Roman",
                    fontsize: int = 12,
                    invisible_text: bool = True,
                    dpi: int = 300):
        """
        Generates a PDF/A document from a hOCR document.
        """

        width, height = None, None
        # Get the image dimensions
        for div in hocr.findall(".//div[@class='ocr_page']"):
            coords = self._element_coordinates(div)
            pt_coords = self._pt_from_pixel(coords, dpi)
            width, height = pt_coords['x2'] - pt_coords['x1'], pt_coords['y2'] - pt_coords['y1']
            # after catch break loop
            break
        if width is None or height is None:
            raise ValueError("Could not determine page size")

        pdf = Canvas(out_filename, pagesize=(width, height), pageCompression=1)

        span_elements = [element for element in hocr.iterfind(".//span")]
        for line in span_elements:
            if 'class' in line.attrib and line.attrib['class'] == 'ocr_line' and line is not None:
                # get information from xml
                pxl_line_coords = self._element_coordinates(line)
                line_box = self._pt_from_pixel(pxl_line_coords, dpi)

                # compute baseline
                slope, pxl_intercept = self._get_baseline(line)
                if abs(slope) < 0.005:
                    slope = 0.0
                angle = atan(slope)
                cos_a, sin_a = cos(angle), sin(angle)
                intercept = pxl_intercept / dpi * inch
                baseline_y2 = height - (line_box['y2'] + intercept)

                # configure options
                text = pdf.beginText()
                text.setFont(fontname, fontsize)
                pdf.setFillColor(black)
                if invisible_text:
                    text.setTextRenderMode(3)  # invisible text

                # transform overlayed text
                text.setTextTransform(cos_a, -sin_a, sin_a, cos_a, line_box['x1'], baseline_y2)

                elements = line.findall(".//span[@class='ocrx_word']")
                for elem in elements:
                    elemtxt = self._get_element_text(elem).strip()
                    # replace unsupported characters
                    elemtxt = elemtxt.translate(str.maketrans(
                        {'ﬀ': 'ff', 'ﬃ': 'f‌f‌i', 'ﬄ': 'f‌f‌l', 'ﬁ': 'fi', 'ﬂ': 'fl'}))
                    if not elemtxt:
                        continue

                    # compute string width
                    pxl_coords = self._element_coordinates(elem)
                    box = self._pt_from_pixel(pxl_coords, dpi)
                    box_width = box['x2'] - box['x1']
                    font_width = pdf.stringWidth(elemtxt, fontname, fontsize)

                    # Adjust relative position of cursor
                    cursor = text.getStartOfLine()
                    dx = box['x1'] - cursor[0]
                    dy = baseline_y2 - cursor[1]
                    text.moveCursor(dx, dy)

                    # suppress text if it is 0 units wide
                    if font_width > 0:
                        text.setHorizScale(100 * box_width / font_width)
                        text.textOut(elemtxt)
                pdf.drawText(text)

        # overlay image if provided
        if image is not None:
            pdf.drawImage(ImageReader(Image.fromarray(image)), 0, 0, width=width, height=height)
        pdf.save()


# Second get the results from doctr OCR
from doctr.models import ocr_predictor
from doctr.io import DocumentFile

model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True)

img_docs = DocumentFile.from_images(["1.jpg", "2.jpg"])

result = model(img_docs)

# Third, export the results to PDF/A which has a overlayed textlayer and is now searchable in any pdf viewer

# returns: list of tuple where the first element is the (bytes) xml string and the second is the ElementTree
xml_outputs = result.export_as_xml()

# init the above parser
parser = HocrParser()

# iterate through the xml outputs and images and export to pdf/a
# the image is optional else you can set invisible_text=False and the text will be printed on a blank page
for i, (xml, img) in enumerate(zip(xml_outputs, img_docs)):
    xml_element_tree = xml[1]
    parser.export_pdfa(f'{i}.pdf', hocr=xml_element_tree, image=img)
```

**Comment by fg-mindee** [comment]
Mmmh I didn't realize we needed that amount of code to turn it into PDF/a. Three questions:
- I'm not very knowledgeable about PDF/a format, do this yield an actual PDF?
- Is there a way to shorten the snippet?
- if not, are there things we can integrate into docTR without changing the dependencies?

**Comment by felixdittrich92** [comment]
@fg-mindee 

1. yes it does not only convert the image to a pdf file also it adds the invisible textlayer on top (for example to search any information into the text and mark the position in any pdf viewer) or create a blank pdf and add the text (printed) on top
2. this snippet is currently shorten to the must need functionality my original script was much longer :smile: 
3. i would love to integrate this directly in docTR to make it easy to use but i think there is no way without adding a dependency (reportlab is the lightest we can take)

`License: BSD License (BSD license (see license.txt for details), Copyright (c) 2000-2018, ReportLab Inc.)`
[Reportlab](https://pypi.org/project/reportlab/)
Overview about reportlabs deps: [Deps](https://archlinux.org/packages/community/x86_64/python-reportlab/)

What do you think integrate with one more dep or provide as example ? (i would prefer the integration :sweat_smile: )

**Comment by felixdittrich92** [comment]
@fg-mindee 
any updates ? :hugs:

**Comment by fg-mindee** [comment]
Making the result a searchable PDF is a really nice feature. However, we need to keep features where they ought to be. In this case, I'd have to investigate the compatibility of the BSD license with Apache 2, and check the dependencies. This feels weird not having access to the source code of this :sweat_smile: 

So for now, I'd say we should investigate alternatives that are both open source, with a compatible license & with minimal dependencies :smile: That's a bit restrictive but I'd argue it does make sense considering this is on the edge of docTR's scope.

**Comment by felixdittrich92** [comment]
@fg-mindee 
i will investigate and update if i have some results / alternatives

**Comment by felixdittrich92** [comment]
@fg-mindee 
i have faiced that it seems to be no way to do this with pure python and without extra deps. 
And the most librarys i have found build on top of reportlab or on top of linux packages
[hocr2pdf](http://manpages.ubuntu.com/manpages/trusty/man1/hocr2pdf.1.html)
[xhtml2pdf](https://github.com/xhtml2pdf/xhtml2pdf/blob/master/requirements.txt)
[hocr-tools](https://github.com/ocropus/hocr-tools/blob/master/requirements.txt)
So its a little bit tricky :sweat_smile: 

more ideas or decisions? :smile:

**Comment by fg-mindee** [comment]
Thanks a lot for the investigation, much appreciated :pray: 
For now, I think we should keep it out of docTR. But making a notebook tutorial about that would be most beneficial!

I have to initiate the tutorial notebooks quite soon anyway so I suggest that we just wait until I submitted the first draft. Then we'll use the same process to add another notebook for this with reportlab! What do you think? :smile:

**Comment by felixdittrich92** [comment]
@fg-mindee 
Lets say it is better as nothing :sweat_smile: 
Why i am so focused to integrate it ? 
tesseract is currently the only open source lib which provides some feature (but tesseract is for DL standards really old, ressource hungry and not really fast and hard to tune on own cases) 
`pdf = pytesseract.image_to_pdf_or_hocr('test.png', extension='pdf')`
DocTR would be benefit from a super easy solution like `export_as_pdf` 

By the way i have found the source: [reportlab-mirror](https://github.com/MrBitBucket/reportlab-mirror)

**Comment by fg-mindee** [comment]
> Lets say it is better as nothing :sweat_smile:

Well it's not nothing, because it comes with inconveniences (license, dependencies, the constraint of keeping that part as tested as the rest of the library, etc.). I fully understand the benefits, but again if there was a Github project with Apache 2 or MIT license and minimal dependencies, we would go for it! I just checked the mirror, it is a full copyright, not an open source license, so I'm glad we check because it's completely incompatible with our open source license :sweat_smile: _(as of now, we're already gonna run into troubles with PyMuPDF because of its less permissive open source license)_

As an author & maintainer, I have to ensure the stability, maintainability, and well-being of the project in the long-term. And here, the safe option would be to postpone that to the moment where we either identify a project meeting our needs, or that we allocate efforts to build this from scratch.

So let's write a notebook as you suggested, and stick to that while there are no alternatives or that we can do it ourselves :+1:

**Comment by felixdittrich92** [comment]
@fg-mindee :+1: 
i will prepare a colab notebook and take again a look if i can simplify thinks :)
And take a bit deeper look how reportlab the thinks do which i would need from their library

**Comment by felixdittrich92** [comment]
@fg-mindee 
i have created a notebook take a look if you want :smile: 
If you are ready with the tutorial stuff we can make it a bit prettier but overall thats it :hugs: 
[Colab Notebook](https://colab.research.google.com/drive/1_gP3yVQdHpw43LAvGGaWsuKGKj775xFT?usp=sharing)

**Comment by fg-mindee** [comment]
Looks very neat thanks!
I'll ping you here once I setup the notebook integration :+1:
