### ISSUE TITLE
Adding pretrained models MASTER and SAR (pytorch)

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#576]
### 🚀 The feature

@fg-mindee 
Adding default pretrained models for `master ` and `Sar` in pytorch
What do you think ? 

### Motivation, pitch

make all current models usable with pretrained

**Comment by fg-mindee** [comment]
Hi @felixdittrich92,

About both:
- We had to debug the `master` in PyTorch with @charlesmindee, we'll release the checkpoint soon
- and regarding the `sar`, I must admit we have deprioritized it since it's really slow. But we'll bridge the gap as well!

**Comment by frgfm** [comment]
Perhaps we should merge this issue with #802 ?

**Comment by felixdittrich92** [comment]
Yes :)

**Comment by felixdittrich92** [comment]
closed with merge in #802
