### ISSUE TITLE
Fine tune Detection and Recognition models on custom dataset

### ISSUE THREAD

**Issue by hkhanr** [mindee/doctr#638]
### Discussed in https://github.com/mindee/doctr/discussions/637

<div type='discussions-op-text'>

<sup>Originally posted by **hkhanr** November 18, 2021</sup>
Hello,

I want to fine-tune detection and recognition models on my custom dataset. 
I have annotated few document images. I converted these annotation to the format mention in the following link [https://github.com/mindee/doctr/tree/main/references/detection](url) and finetuned a detection model. Now I want to finetune the recognition model. However, the given link doesn't clearly tells what should be the annotation format [https://github.com/mindee/doctr/tree/main/references/recognition](url). I mean the given link doesn't tells how to associate the GT box/polygon with GT text. 
My question is, how to associate GT polygon with GT text in polygon while training recognition model?</div>

**Comment by fg-mindee** [comment]
Hi there :wave: 

Please don't open duplicate issue/discussion on the repo :pray: 
Let's continue this topic on the discussion :+1:
