### ISSUE TITLE
Detection on image part not working

### ISSUE THREAD

**Issue by LCMA7** [mindee/doctr#639]
Hi,

I tried to use docTR on a part of an image, but it does not seems to work .
Here is the full image, the part image, the code and the output obtained :

### **Input**
![2](https://user-images.githubusercontent.com/85179628/142606100-0da6406e-9b96-42cd-9ecd-7ec333e58a48.jpg)
![5](https://user-images.githubusercontent.com/85179628/142606097-fa7e0320-3f1c-4ee6-b255-17d5091929ed.jpg)

### **Code**
```
from doctr.models import ocr_predictor
from doctr.io import DocumentFile

model = ocr_predictor(reco_arch='sar_resnet31', pretrained=True)
multi_img_doc = DocumentFile.from_images(["2.jpg", "4.jpg"])
result = model(multi_img_doc)
result.show(multi_img_doc)
result
```

### **Output**
![image](https://user-images.githubusercontent.com/85179628/142606538-318649c3-7210-4ec1-9743-da2ad780caec.png)
![image](https://user-images.githubusercontent.com/85179628/142606537-74d72e53-ecb0-49c2-b0d8-f32c2f526ea3.png)

```
Document(
  (pages): [
    Page(
      dimensions=(194, 259)
      (blocks): [Block(
        (lines): [Line(
          (words): [
            Word(value='15:11', confidence=0.23),
            Word(value='60', confidence=0.47),
            Word(value='50', confidence=0.49),
            Word(value='141.8', confidence=0.45),
            Word(value='182669', confidence=0.88),
            Word(value='-', confidence=0.83),
            Word(value='a', confidence=0.42),
            Word(value='20', confidence=0.65),
            Word(value='190', confidence=0.37),
          ]
        )]
        (artefacts): []
      )]
    ),
    Page(
      dimensions=(28, 53)
      (blocks): []
    ),
  ]
)
```

**What can I do to get the same detection and recognition on this image part ?**

Thank you in advance.

**Comment by fg-mindee** [comment]
Hi @LCMA7 :wave: 

Thanks for bringing this up! So the underlying problem here is the scale robustness of our text detection module (the part that localizes the text), which was trained on documents and not crops/subparts.
So to answer your question:
- what you can do: if you already have the localization of the textual elements, send them directly to a RecognitionPredictor
```python
from doctr.models import ocr_predictor
from doctr.io import DocumentFile

predictor = ocr_predictor(reco_arch='sar_resnet31', pretrained=True)
multi_img_doc = DocumentFile.from_images(["2.jpg", "4.jpg"])
res1 = predictor(multi_img_doc[:1])
res1.show(multi_img_doc[:1])
res1

res2 = predictor.reco_predictor(multi_img_doc[1:])
res2
```
- what we will do in the future: make the detection more robust to scale variety, have a smarter resizing & padding scheme!

I hope this helps, let me know if some details are unclear!

**Comment by fg-mindee** [comment]
Closing this as it looks like you approved my previous answer @LCMA7 :+1: 
If that's not the case, feel free to reopen!

**Comment by akarshsoman** [comment]
@fg-mindee  i tried it with a cropped image but the result is null
i used craft for text detection 
![img1](https://user-images.githubusercontent.com/25591311/164704770-1d451006-3236-4048-a983-fcbc67f5b9eb.jpg)
.
