### ISSUE TITLE
Assertion error when using assume_straight_pages=False

### ISSUE THREAD

**Issue by Rob192** [mindee/doctr#646]
### Bug description

When I am using `assume_straight_pages=False` in the `OCRPredictor` I am getting an Assertion error since #641 

### Code snippet to reproduce the bug

```python
from pathlib import Path

import matplotlib.pyplot as plt

from doctr.io import DocumentFile
from doctr.models.detection.zoo import detection_predictor
from doctr.models.predictor.tensorflow import OCRPredictor
from doctr.models.recognition.zoo import recognition_predictor
from doctr.utils.visualization import visualize_page

file = Path(r"C:\Users\Utilisateur\PythonProjects\ocr-xtract\data\aaaaa_straight.jpg") 

doc = DocumentFile.from_images(file)
det_bs=2
reco_bs=128

det_predictor = detection_predictor('db_resnet50', pretrained=True, batch_size=det_bs)
reco_predictor = recognition_predictor('crnn_vgg16_bn', pretrained=True, batch_size=reco_bs)

predictor = OCRPredictor(det_predictor=det_predictor, reco_predictor=reco_predictor, assume_straight_pages=False)

# Plot OCR output
out = predictor(doc)

fig = visualize_page(out.pages[0].export(), doc[0], interactive=False)
plt.show()
```

![aaaaa_straight](https://user-images.githubusercontent.com/33607785/143246053-89b5f292-b8d8-41a7-9730-9d95b0c5a115.jpg)

### Error traceback

```
Traceback (most recent call last):
  File "C:/Users/Utilisateur/PythonProjects/doctr/scripts/test_image.py", line 44, in <module>
    out = predictor(doc)
  File "C:\Users\Utilisateur\PythonProjects\doctr\doctr\models\predictor\tensorflow.py", line 62, in __call__
    crops, loc_preds = self._prepare_crops(
  File "C:\Users\Utilisateur\PythonProjects\doctr\doctr\models\predictor\base.py", line 49, in _prepare_crops
    crops = _OCRPredictor._generate_crops(pages, loc_preds, channels_last, assume_straight_pages)
  File "C:\Users\Utilisateur\PythonProjects\doctr\doctr\models\predictor\base.py", line 35, in _generate_crops
    crops = [
  File "C:\Users\Utilisateur\PythonProjects\doctr\doctr\models\predictor\base.py", line 36, in <listcomp>
    extraction_fn(page, _boxes[:, :-1], channels_last=channels_last)  # type: ignore[operator]
  File "C:\Users\Utilisateur\PythonProjects\doctr\doctr\models\_utils.py", line 69, in extract_rcrops
    raise AssertionError("boxes are expected to be relative and in order (x, y, w, h, alpha)")
AssertionError: boxes are expected to be relative and in order (x, y, w, h, alpha)
```

### Environment

```
DocTR version: 0.4.1a0
TensorFlow version: 2.5.0
PyTorch version: 1.9.1+cpu (torchvision 0.10.1+cpu)
OpenCV version: 4.5.2
OS: Could not collect
Python version: 3.8.7
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): No
CUDA runtime version: 11.0.221
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
```

**Comment by charlesmindee** [comment]
Hi @Rob192, 

This should be fixed when merging the PR #647.

Now that we have the `assume_straight_pages option`, you need to pass it in the Detection predictor. You have 2 options:
- You can use the high-level function `ocr_predictor(assume_straight_pages=True)` (which will pass the flag through the detection predictor). 
- If you wan to instantiate an `OCRPredictor` as you did from a `detection_predictor` and a `recognition_predictor`, you need to specify `assume_straight_pages=True` in the detection predictor: `detection_predictor(assume_straight_pages=True)`.

I hope this help you!

**Comment by Rob192** [comment]
Hi @charlesmindee,
Ok thanks ! My issue arises when I set `assume_straight_pages=False`. I think this comes from the fact that `extract_rcrops` outputs arrays of `shape[1]==5` and they should be of `shape[1]==6`.

**Comment by charlesmindee** [comment]
Hi @Rob192, 
Are you sure this is still an issue ?
This code is running correctly on my computer (after #647):

```
from pathlib import Path
from pathlib import Path

import matplotlib.pyplot as plt

from doctr.io import DocumentFile
from doctr.models.detection.zoo import detection_predictor
from doctr.models.predictor.tensorflow import OCRPredictor
from doctr.models.recognition.zoo import recognition_predictor
from doctr.utils.visualization import visualize_page

file = Path(r"path/my_picture") 

doc = DocumentFile.from_images(file)
det_bs=2
reco_bs=128

det_predictor = detection_predictor('db_resnet50', pretrained=True, batch_size=det_bs, assume_straight_pages=False)
reco_predictor = recognition_predictor('crnn_vgg16_bn', pretrained=True, batch_size=reco_bs)

predictor = OCRPredictor(det_predictor=det_predictor, reco_predictor=reco_predictor, assume_straight_pages=False)

# Plot OCR output
out = predictor(doc)

fig = visualize_page(out.pages[0].export(), doc[0], interactive=False)
plt.show()
```

**Comment by Rob192** [comment]
Oh Ok !!! I did not properly understood your answer. I was not passing `assume_straight_pages` to the `detection_predictor` ! It's fixed now thanks ! I am closing this.

**Comment by Shishir-Suman** [comment]
Still seems to throw me the same error. Anyone successfully ran the above code block with the latest version?
AssertionError: boxes are expected to be relative and in order (x, y, w, h, alpha)

**Comment by fg-mindee** [comment]
> Still seems to throw me the same error. Anyone successfully ran the above code block with the latest version? AssertionError: boxes are expected to be relative and in order (x, y, w, h, alpha)

Hi @Shishir-Suman :wave: 
On my end, I just tried with the last commit of the "main" branch and the code runs successfully!
Have you installed this in developer mode to have the latest codebase version?

cf. https://github.com/mindee/doctr#developer-mode

**Comment by Rob192** [comment]
@Shishir-Suman for me what resolved the error is to ask the det_predictor for straight of rotated boxes : 
`det_predictor = detection_predictor('db_resnet50', pretrained=True, batch_size=det_bs, assume_straight_pages=False)`

see @charlesmindee [snippet ](https://github.com/mindee/doctr/issues/646#issuecomment-978955629)
