### ISSUE TITLE
OSError: no library called "cairo"/cairo2 was found in Windows

### ISSUE THREAD

**Issue by JMaximilian** [mindee/doctr#701]
### Bug description
Error when important the library in python. 

Steps I took: 
1. Install [GTK ](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases)
2.  Created a new venv
3.  pip install "python-doctr[tf]

### Code snippet to reproduce the bug

Both lines throw the same error in Python. 
```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
```

### Error traceback

```
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8712/4102879070.py in <module>
----> 1 from doctr.models import ocr_predictor

C:\Python\Python37\lib\site-packages\doctr\__init__.py in <module>
----> 1 from . import datasets, io, models, transforms, utils
      2 from .file_utils import is_tf_available, is_torch_available
      3 from .version import __version__  # noqa: F401

C:\Python\Python37\lib\site-packages\doctr\datasets\__init__.py in <module>
      1 from doctr.file_utils import is_tf_available
      2 
----> 3 from .classification import *
      4 from .cord import *
      5 from .detection import *

C:\Python\Python37\lib\site-packages\doctr\datasets\classification\__init__.py in <module>
      2 
      3 if is_tf_available():
----> 4     from .tensorflow import *
      5 elif is_torch_available():
      6     from .pytorch import *  # type: ignore[misc]

C:\Python\Python37\lib\site-packages\doctr\datasets\classification\tensorflow.py in <module>
      6 import tensorflow as tf
      7 
----> 8 from .base import _CharacterGenerator
      9 
     10 __all__ = ['CharacterGenerator']

C:\Python\Python37\lib\site-packages\doctr\datasets\classification\base.py in <module>
      8 from PIL import Image, ImageDraw
      9 
---> 10 from doctr.io.image import tensor_from_pil
     11 from doctr.utils.fonts import get_font
     12 

C:\Python\Python37\lib\site-packages\doctr\io\__init__.py in <module>
      1 from .elements import *
----> 2 from .html import *
      3 from .image import *
      4 from .pdf import *
      5 from .reader import *

C:\Python\Python37\lib\site-packages\doctr\io\html.py in <module>
      6 from typing import Any
      7 
----> 8 from weasyprint import HTML
      9 
     10 __all__ = ['read_html']

C:\Python\Python37\lib\site-packages\weasyprint\__init__.py in <module>
    467 
    468 # Work around circular imports.
--> 469 from .css import preprocess_stylesheet  # noqa isort:skip
    470 from .html import (  # noqa isort:skip
    471     HTML5_UA_COUNTER_STYLE, HTML5_UA_STYLESHEET, HTML5_PH_STYLESHEET,

C:\Python\Python37\lib\site-packages\weasyprint\css\__init__.py in <module>
     25 from ..logger import LOGGER, PROGRESS_LOGGER
     26 from ..urls import URLFetchingError, get_url_attribute, url_join
---> 27 from . import computed_values, counters, media_queries
     28 from .properties import INHERITED, INITIAL_NOT_COMPUTED, INITIAL_VALUES
     29 from .utils import get_url, remove_whitespace

C:\Python\Python37\lib\site-packages\weasyprint\css\computed_values.py in <module>
     13 from tinycss2.color3 import parse_color
     14 
---> 15 from .. import text
     16 from ..logger import LOGGER
     17 from ..urls import get_link_attribute

C:\Python\Python37\lib\site-packages\weasyprint\text.py in <module>
      9 import re
     10 
---> 11 import cairocffi as cairo
     12 import cffi
     13 import pyphen

C:\Python\Python37\lib\site-packages\cairocffi\__init__.py in <module>
     48 cairo = dlopen(
     49     ffi, ('cairo-2', 'cairo', 'libcairo-2'),
---> 50     ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
     51 
     52 

C:\Python\Python37\lib\site-packages\cairocffi\__init__.py in dlopen(ffi, library_names, filenames)
     43     error_message = '\n'.join(  # pragma: no cover
     44         str(exception) for exception in exceptions)
---> 45     raise OSError(error_message)  # pragma: no cover
     46 
     47 

OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

### Environment

Windows 10
Python 3.7.9
TensorFlow  2.6.2
GTK 2021-04-29 (latest)
python-doctr 0.4.1

**Comment by fg-mindee** [comment]
Hi @JMaximilian :wave: 

I've tried to reproduce this error but it is a bit tricky as we don't have many people around with Windows setups. However from the error message that you got, I understand that cairo isn't installed in your environment.

In the documentation, we added instructions on how to handle this, which are directly taken from the installation instructions of the one dependency that throws this (weasyprint): https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#windows

Would you mind trying to follow those instructions above and try to run the following command:
```python
from weasyprint import HTML
```
?

If this commands doesn't work, the problem is admittedly on weasyprint side. Otherwise it's on ours :sweat_smile: 

I hope this helps!

**Comment by JMaximilian** [comment]
Hi @fg-mindee,

Thanks for your response. Indeed the weasyprint HTML import throws the same error. 

So the error is not on your side but on weasyprint.  
Unfortunately, their documentation is not providing a working solution for me.

**Comment by fg-mindee** [comment]
Sorry about this!

I've read several times that the problem may come from the incompatibility between 32bits / 64bits systems. I would suggest checking the official GTK installation page over here :point_right: https://www.gtk.org/docs/installations/windows/

**Comment by fg-mindee** [comment]
Out of curiosity @JMaximilian, did you manage to solve your problem (even though it's from an external dependency)?
We're going to try to reproduce the bug, but it's usually quite tricky considering how installing some Python deps require extra specific steps on Windows :sweat_smile:

**Comment by mat-l** [comment]
Dear @JMaximilian, I am also running into the same problem. Could you please give me a hint how you have solved it?

**Comment by JMaximilian** [comment]
Hi @mat-l 

Did you already check whether the issue comes from weasyprint? 
`from weasyprint import HTML`

My "solution" was installing it on another system, and there it worked. 
When installing take care to install GTK first, before docTR.  Sorry I cannot be more of a help.
