### ISSUE TITLE
[Models] Add SAR teacher forçing during training (decoder)

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#71]
Teacher forçing (feeding the LSTM decoder of SAR with ground-truth characters during training) is not implemented, and it should really improve performances

**Comment by fg-mindee** [comment]
Could you elaborate on the part of the paper where this is mentioned please? :pray:

**Comment by charlesmindee** [comment]
"All the LSTM inputs are represented by one-hot vectors, followed by a linear ransformationΨ(). During training, the inputs of decoder LSTMs are replaced by the ground-truth character sequence"
