### ISSUE TITLE
[notebooks] Add a notebook tutorial on artefact detection

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#732]
The artefact detection feature is a really nice one, and we should help users to leverage it in the most efficient way. I believe that a notebook tutorial would be a good way to do so, what do you think @SiddhantBahuguna?

**Comment by SiddhantBahuguna** [comment]
I completely agree with you. I am on it!
Thanks :)

**Comment by fg-mindee** [comment]
Now that https://github.com/mindee/notebooks/pull/5 has been merged, would you mind opening a PR here to add a new row in this table https://github.com/mindee/doctr/blob/main/notebooks/README.md ? :)

That will automatically deploy it in the documentation (https://mindee.github.io/doctr/latest/notebooks.html)

**Comment by SiddhantBahuguna** [comment]
> Now that [mindee/notebooks#5](https://github.com/mindee/notebooks/pull/5) has been merged, would you mind opening a PR here to add a new row in this table https://github.com/mindee/doctr/blob/main/notebooks/README.md ? :)
> 
> That will automatically deploy it in the documentation (https://mindee.github.io/doctr/latest/notebooks.html)

Thanks for the further guidance!
A PR has been opened:)

**Comment by fg-mindee** [comment]
The issue shouldn't be closed before the PR is merged!

**Comment by SiddhantBahuguna** [comment]
> The issue shouldn't be closed before the PR is merged!

Oh my bad :) Thanks
