### ISSUE TITLE
ImportError: cannot import name 'db_resnet50_rotation' from 'doctr.models.detection' 

### ISSUE THREAD

**Issue by devendrapal5755** [mindee/doctr#852]
### Bug description

facing to import 'doctr.models.detection ,
 abele to import  others detection model but cant import db_resnet50_rotation  

### Error traceback

everything is perfect, but now facing this issues from last 5 days before it was working 

### Environment

na

**Comment by felixdittrich92** [comment]
@devendrapal5755 
Do you have installed both tf and pt ? If yes please check that pt is used :) (export USE_PT=1)

**Comment by fg-mindee** [comment]
Hello @devendrapal5755 :wave: 

Thanks for reporting this! Let's get to the bottom of this:
- first, you mentioned that the import causes an error. It's always useful to paste the full traceback for us to debug :)
- as suggested by the bug report template, in most cases, this type of problem comes from an environment issue. But you didn't provide your environment setup (there is a script just for that). Would you mind running the following command & paste the console output please?
```shell
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- as of now `db_resnet50_rotation` is only available with PyTorch backend, so @felixdittrich92 hint might be right. I can see two reasons with the current information: either you're running a version of docTR that doesn't have this model, or you are running TensorFlow backend. The result of the environment collection script should help us answer that question :+1: 

Let us know if you run into any trouble in the process!

Cheers :v:

**Comment by devendrapal5755** [comment]
Thank You.  I understand and resolved it.

**Comment by fg-mindee** [comment]
Glad it helped! @devendrapal5755 would you mind sharing what the issue was? :)

**Comment by devendrapal5755** [comment]
I faced error due to install like - 1-git clone https://github.com/mindee/doctr.git
                                                    2-pip install -e doctr/.
                                                    3-pip install -e doctr/.[torch]  
now i simply installed by - !pip install python-doctr[torch]
                                            !pip install -e git+https://github.com/mindee/doctr.git
