### ISSUE TITLE
Pretrained model checkpoint for SAR and MASTER in pytorch

### ISSUE THREAD

**Issue by Bhanu068** [mindee/doctr#854]
### Bug description

I could see that pretrained checkpoint is available for tensorflow version of the SAR and MASTER recogniton models but not for pytorch version. How can I get the pretrained checkpoint for pytorch version?

### Code snippet to reproduce the bug

None

### Error traceback

None

### Environment

pytorch

**Comment by felixdittrich92** [comment]
Hi @Bhanu068 :wave: ,

take a look at #576  :)

**Comment by fg-mindee** [comment]
Hi @Bhanu068 :)

As mentioned by Felix, we are trying to fix this currently! There are other issues already opened on that matter, so if you agree that #576 already expresses your request, perhaps we could close this one here to avoid duplication :ok_hand: 
Would that be OK with you?

**Comment by felixdittrich92** [comment]
@charlesmindee @Bhanu068 can be closed ? :)
