### ISSUE TITLE
[models] Pretrained artefact detection model isn't that robust

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#863]
The current pretrained artefact detection model was trained on a fully synthetic dataset. While this comes with several advantages, the dataset has a distribution that is still a bit far off from real-world data.

This is almost a product question but users can either use this on:
- source PDF/documents
- scanned documents
- pictures of documents

While the model performs quite well on the first two usecases, the last one has some precision troubles sometimes (especially with the background):

![image](https://user-images.githubusercontent.com/76527547/158847946-67e10872-0d97-4736-acdc-b3f9e1daa965.png)

To tackle this, perhaps we should improve the dataset or add nice augmentations that adds backgrounds instead of zero padding for geometric transforms (rotation, perspective, etc.)

What do you think @SiddhantBahuguna?

cc @fharper

**Comment by felixdittrich92** [comment]
@SiddhantBahuguna any update ? :)

**Comment by felixdittrich92** [comment]
On user end with contrib module now
