### ISSUE TITLE
Export as PDF/A

### ISSUE THREAD

**Issue by bennetrr** [mindee/doctr#872]
### 🚀 The feature

A function in the Document class or something that allows you to save the original document with the OCR to a PDF/A file

### Motivation, pitch

There is this [notebook](https://github.com/mindee/notebooks/blob/main/doctr/export_as_pdfa.ipynb), but we have to define our own parser and so on, and that's a lot of code to write and maintain even though we don't know much about it.

**Comment by felixdittrich92** [comment]
Link: #869

**Comment by felixdittrich92** [comment]
@frgfm
Advice from your side ? :)

**Comment by bennetrr** [comment]
We can give you the PDF where the problems occur, but it takes some time because we have to ask the owners first. We deleted all information, so they should be fine I think

**Comment by felixdittrich92** [comment]
@bennetrr any update ? :)

**Comment by bennetrr** [comment]
> We recently had to change our pdf rendering dependency

So, doctr is able to export the pdf into a not PDF/A file?

**Comment by frgfm** [comment]
> > We recently had to change our pdf rendering dependency
> 
> So, doctr is able to export the pdf into a not PDF/A file?

As mentioned in the notebook, no, docTR isn't able to do this currently.
However, docTR outputs enough information to recreate a PDF/A from it. Onboarding license & dependency constraints for something that users can easily implement isn't necessarily ideal

But we're quite open to user's feedback & suggestions :) If you have ideas to share, feel free to do so!
