### ISSUE TITLE
Mode inference error on GPU/cuda

### ISSUE THREAD

**Issue by as-stevens** [mindee/doctr#877]
Hi All,

I am trying to load the model and prediction using the below code;
```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
import torch
predictor = ocr_predictor('db_resnet50', 'crnn_vgg16_bn', pretrained=True).cuda()
image_path = 'test_image.jpg'
img = DocumentFile.from_images([image_path])
result = predictor(img)
print(type(result)) 
```

I am getting the below error;

`RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor`

Any idea what is wrong, I have Nvidia RTX A6000 GPU, with cuda installed.

Thanks

**Comment by Ryul0rd** [comment]
Are you using DocTR version 0.5.1? I came across this issue while I was still on 0.5.0 and updating fixed it.

**Comment by as-stevens** [comment]
I have been able to fix this;
converted the tensor to tensor cuda as below
```
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
img = read_img_as_tensor(image_path).unsqueeze(0)
img = img.cuda(device)
result = predictor(img)
```
@Ryul0rd the above solution fixed my issue.
