### ISSUE TITLE
Can I add some vocabs of Vietnamese to VOCABS file ?

### ISSUE THREAD

**Issue by calibretaliation** [mindee/doctr#879]
### 🚀 The feature

I have added vietnamese vocabs for VNese devs like me to use doctr better, following this issue: https://github.com/mindee/doctr/pull/464#pullrequestreview-752843039
This is my pull request, please review it.

### Motivation, pitch

I am very appreciate and congrats on your great work. This package will help me alot in my work :) However, I am working on Vietnamese OCR, so Vietnamese vocabs is required and I can't see any guide to locally added vietnamese vocabs without changing the main repository (which I am quite afraid of damaging something I dont know). It would be very nice if you could guide me or review my contribution on vietnamese vocabs here: https://github.com/mindee/doctr/pull/878

### Additional context

And please, if you agree with my contribution, can you also give me soem tips on how to apply the new vocab in your work ? Are there any tools or guide line on how to create and train a custom dataset ?
Thank you very much ~!

**Comment by Xargonus** [comment]
Hey, I am in a similar situation, but in my case, I need a model for Czech. I found the advice they gave to someone who wanted to train the text recognition model in Spanish useful https://github.com/mindee/doctr/discussions/565.

**Comment by felixdittrich92** [comment]
@charlesmindee 
Can be closed ? :)

**Comment by kiko0217** [comment]
just simple, transfer learning maybe can be solution. edit little in end layer and then learning the model with your custom data.
