### ISSUE TITLE
Can not make prediction using any model other than db  and crnn models

### ISSUE THREAD

**Issue by EMRAN-SALEH-CORSEARCH** [mindee/doctr#898]
### Bug description

I have tested the prediction of the system using the pytorch version. The system Can not make prediction using any model other than db  and crnn model. It gives this message: 
"WARNING:root:Invalid model URL, using default initialization."

Looks like there is an error with the links to download the pretrained models for all the other detection and recognition models. 

### Code snippet to reproduce the bug

model = ocr_predictor(det_arch='linknet_resnet18', reco_arch='sar_resnet31', pretrained=True)

### Error traceback

WARNING:root:Invalid model URL, using default initialization.
WARNING:root:Invalid model URL, using default initialization.

### Environment

python

### Deep Learning backend

is_tf_available: False
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @EMRAN-SALEH-CORSEARCH 👋 ,
that's true linknet / sar and master does currently not have pretrained versions and sar + master needs some fixes but it's on track for 0.6.0 :)

**Comment by charlesmindee** [comment]
closing this since it is a replicate of #576, thanks!
