### ISSUE TITLE
there is a erroe on windows

### ISSUE THREAD

**Issue by dingli06** [mindee/doctr#899]
### Bug description

my os is windows
when  I use it to predict
it happens:
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\Graphviz2.38\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

### Code snippet to reproduce the bug

OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\Graphviz2.38\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

### Error traceback

OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\Graphviz2.38\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

### Environment

OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\Graphviz2.38\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

### Deep Learning backend

OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\Graphviz2.38\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

**Comment by felixdittrich92** [comment]
Hi @dingli06 👋 ,
There is currently a closed issue about this can you please try if it help #701 ? :)

**Comment by dingli06** [comment]
> Hi @dingli06 👋 , There is currently a closed issue about this can you please try if it help #701 ? :)

thanks, I have solve it

**Comment by felixdittrich92** [comment]
@dingli06 👍 
@charlesmindee please close :)

**Comment by charlesmindee** [comment]
Thanks @felixdittrich92
