### ISSUE TITLE
Add information on PR labelling process

### ISSUE THREAD

**Issue by fharper** [mindee/doctr#907]
### 🚀 The feature

Add information in the contribution documentation about PR labelling process

### Motivation, pitch

I can't add the labels myself to the PR as I'm not quite sure what to put when, and what is happening depending on the requirement.

### Alternatives

I need to ask @charlesmindee to do it for me all the time 😅

**Comment by frgfm** [comment]
Hey there @fharper :) 

So, the constraints are written over here 👉 https://github.com/mindee/doctr/blob/main/.github/verify_pr_labels.py#L17-L42

And I'll investigate why it's not working anymore, but initially, the bot was flagging PRs that were wrongly labeled:
- last PR I passed to make it work: https://github.com/mindee/doctr/pull/792
- last illustration of the bot picking up a wrongly labeled PR https://github.com/mindee/doctr/pull/829#issuecomment-1050033214

Let me know if that isn't enough, but if we need further instructions, considering it's only for maintainers, I'd argue it doesn't have its place in the documentation. But we could put it in the GH wiki 🤷‍♂️

**Comment by fharper** [comment]
Actually, I think just adding a description to the labels missing ones would be more than enough. WDYT?

**Comment by frgfm** [comment]
It depends what you mean, but there are different levels of information here:
- what each label means (I added some descriptions already)
- which minimum number & category of label should be put on a PR for the release note to be generated smoothly & correctly

For the first part, description would be enough but the second, I would argue it wouldn't 🤷 How do you see the description you mentioned?

**Comment by frgfm** [comment]
I just added a description on each PR/issue label :+1: 
Feel free to reopen if I missed something!
