### ISSUE TITLE
[W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware.

### ISSUE THREAD

**Issue by kiko0217** [mindee/doctr#915]
### Bug description

In linux i got notify [W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware. how to solve this notify?
I use pytorch.

### Code snippet to reproduce the bug

```cmd
pip install torch torchvision torchaudio
```

```python
import os
os.environ['USE_TORCH']= '1'
```

### Error traceback

```
[W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware.
```

### Environment

```
DocTR version: 0.6.0a0
TensorFlow version: N/A
PyTorch version: 1.11.0+cu102 (torchvision 0.12.0+cu102)
OpenCV version: 4.5.5
OS: CentOS Linux 8 (Core)
Python version: 3.9.5
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): No
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
```

### Deep Learning backend

```
is_tf_available: False
is_torch_available: True
```

**Comment by felixdittrich92** [comment]
Hi @kiko0217 :wave:,
this is definitely not a problem created by docTR :sweat_smile: 
But you can take a look at this discussion:
https://discuss.pytorch.org/t/bug-w-nnpack-cpp-80-could-not-initialize-nnpack-reason-unsupported-hardware/107518/19

**Comment by frgfm** [comment]
Hello @kiko0217 👋 

As stated by Felix, this doesn't come from docTR. I suggest trying to [reinstall PyTorch](https://pytorch.org/get-started/locally/) and making sure you can import it in a python shell 👍
