### ISSUE TITLE
[references][tf/pt] Add early stopping callback

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#924]
### 🚀 The feature

Add EarlyStopping callback in references for both frameworks

### Motivation, pitch

To make it easier for users to choose some hyperparameters i would suggest that we add a EarlyStopping callback this would be also useful if you train your model remote (for example AWS)

**Comment by SkaarFacee** [comment]
This is something I would like to work on, could I get more details regarding this ? I haven't quite understood the AWS part

**Comment by felixdittrich92** [comment]
@SkaarFacee any updates ? :)

**Comment by SkaarFacee** [comment]
> @SkaarFacee any updates ? :)

I have made some progress, but had to stop midway due to work commitments. Over the following weekend I hope to solve the issue

**Comment by felixdittrich92** [comment]
> > @SkaarFacee any updates ? :)
> 
> I have made some progress, but had to stop midway due to work commitments. Over the following weekend I hope to solve the issue

Sounds good ☺️
