### ISSUE TITLE
Fix encode_string function

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#927]
### Bug description

Currently there is no check if the single characters are also available in the given vocabulary.
We need a check for this :) 

TODO's:

- [ ] check that in the function and throw a meaningful exception
- [ ] improve the corresponding test 

discussion:
#926 

### Code snippet to reproduce the bug

```python
from doctr.datasets.utils import encode_string
from doctr.datasets import VOCABS

x = encode_string(input_string='abcDÄÜ', vocab=VOCABS['english'])   # Ä and Ü does not exist in vocab
# raises ValueError: substring not found
```

### Error traceback

```
Traceback (most recent call last):
  File "/home/felix/Desktop/doctr/test.py", line 7, in <module>
    x = encode_string(input_string='abcDÄÜ', vocab=VOCABS['english'])   # Ä and Ü does not exist in vocab
  File "/home/felix/Desktop/doctr/doctr/datasets/utils.py", line 75, in encode_string
    return list(map(vocab.index, input_string))  # type: ignore[arg-type]
ValueError: substring not found
```

### Environment

not need :)

### Deep Learning backend

same

**Comment by frgfm** [comment]
Thanks for the issue 🙏 
I'd argue it's a documentation/error message clarity issue rather than a bug (meaning that we don't want the code to stop failing in this snippet)
