### ISSUE TITLE
[Build] Update project build config and setup depend-a-bot

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#957]
### 🚀 The feature

We should update the current build configuration to a more modern one:

- instead of requirements files and a large setup.py use pyproject.toml instead
- for some reasons i would suggest to setup depend-a-bot to tackle some dependency issues and keep it actual

@frgfm i would assign this one to you :)
Is that ok for you ? 

### Motivation, pitch

better dependencies handling
reduce the amount of configuration specific files
hold dependencies up to date

**Comment by frgfm** [comment]
Yes, sounds good! Thanks for opening this tracker :)
I'll deal with this shortly!

**Comment by frgfm** [comment]
I will proceed in several parts:
- [ ] moves existing configs to pyproject.toml for tools (not build) #966 
- [ ] add black formatting
- [ ] moves requirements to pyproject.toml and make version specifier stricter
- [ ] set up the bot

**Comment by felixdittrich92** [comment]
@frgfm do you think we can also change CI to circleci ?

**Comment by frgfm** [comment]
I could, but why do you think it would be better?
In my opinion, considering the project is on Github, and the Github CI has a lot of useful features/actions, it's easier with that :)

**Comment by felixdittrich92** [comment]
Mh yes but i see as a big disadvantage that it is not possible to choose a job specific instance type (for example SAR and MASTER Onnx tests are not possible in both frameworks in fact that it kills the provided instance type by Github CI -> locally works) and i think this will not be the only case .. another think is that we would be much more flexible for example we could scale the CI to specific jobs computation need .. do you know what i mean ? :)

**Comment by felixdittrich92** [comment]
It is only a idea if you have another solution in mind would be also fine :) but we need anything to test also computation expensive workflows in our CI

**Comment by frgfm** [comment]
Yes I get what you mean, but the CI is already cluttered with jobs either way :sweat_smile: 
I'll have to take a look and reassess what needs testing and whether we could do it more efficiently! Just FYI, we have an unusually high amount of features being tested by the CI (in a good way)

**Comment by felixdittrich92** [comment]
> Yes I get what you mean, but the CI is already cluttered with jobs either way 😅 I'll have to take a look and reassess what needs testing and whether we could do it more efficiently! Just FYI, we have an unusually high amount of features being tested by the CI (in a good way)

Yes I know it's more about the fact that we can't test more computationally intensive jobs (like Onnx for SAR/MASTER) due to Github CI's instance limitation :) Otherwise we could maybe annotate these jobs as being only tested locally (like huggingface slow tests)

**Comment by felixdittrich92** [comment]
> Yes I get what you mean, but the CI is already cluttered with jobs either way 😅 I'll have to take a look and reassess what needs testing and whether we could do it more efficiently! Just FYI, we have an unusually high amount of features being tested by the CI (in a good way)

Yes I know it's more about the fact that we can't test more computationally intensive jobs (like Onnx for SAR/MASTER) due to Github CI's instance limitation :) Otherwise we could maybe annotate these jobs as being only tested locally (like huggingface slow tests)

**Comment by frgfm** [comment]
> Yes I know it's more about the fact that we can't test more computationally intensive jobs (like Onnx for SAR/MASTER) due to Github CI's instance limitation :) Otherwise we could maybe annotate these jobs as being only tested locally (like huggingface slow tests)

I would prefer the last option, we need to prioritize what needs testing in docTR :)

**Comment by felixdittrich92** [comment]
Huhu @frgfm 👋 do you think we could wrap this up maybe next week? I think updating the requirements will also solve the docker problem. Then we would be ready for the release 👍 😃

**Comment by frgfm** [comment]
@felixdittrich92 sure :)

**Comment by felixdittrich92** [comment]
@frgfm any updates ? :)
