### ISSUE TITLE
Release tracker - v0.5.2

### ISSUE THREAD

**Issue by frgfm** [mindee/doctr#967]
This issue is to be used to track the roadmap of docTR for release v0.5.2, and collect feedback from users & contributors.

For the v0.5.1 roadmap, please see #788

- Datasets
    - [x] #927
    - [x] #956

- Models
    - [x] #902
    - [x] #960
    - [x] #964
 
- IO
    - [x] #947
    - [x] #953

- API
    - [x] #847 (#997)

- Documentation
    - [x] #901
    - [x] #937
    - [x] #958

- Demo
    - [x] #951 

- Build
    - [x] #932 

- Backlog from v0.5.1:
    - [x] #802

**Comment by felixdittrich92** [comment]
@frgfm Lets finalize this next week i am sure #957 (requirements) will fix the docker issue and #802 is also finished (1 merge left) :hugs:

**Comment by felixdittrich92** [comment]
moved into #791
