### ISSUE TITLE
[models] Complete the list of pretrained available models in TensorFlow and PyTorch

### ISSUE THREAD

**Issue by felixdittrich92** [mindee/doctr#969]
### 🚀 The feature

Ensure that each model has a pretrained available checkpoint

**TensorFlow:**

classification:

- [x] ViT
- [x] MAGC
- [x] MobileNetV3 

detection:

- [x] DB_MobileNetV3
- [X] LinkNet (all)

recognition:

- [x] SAR
- [x] MASTER
- [x] VitSTR (small)
- [x] VitSTR (base)
- [x] PARSeq
- [x] CRNN (mobilenet_v3_large)

**PyTorch:**

classification:

- [x] ViT
- [x] ResNet34_wide (@felixdittrich92)

detection:

- [ ] DB_ResNet34
- [ ] LinkNet (all)

recognition:

- [x] SAR
- [x] MASTER
- [x] VitSTR (small)
- [x] VitSTR (base)
- [x] PARSeq

### Motivation, pitch

- Users wants to test each available model and needs the pretrained versions to finetune on there own data

**Comment by felixdittrich92** [comment]
@charlesmindee i think you are the only one who can do it (data)

**Comment by nikokks** [comment]
@charlesmindee, what kind of data do you use to train your text recogntions models ? 
Do you use custom data ? and do you use special data for french documents ?

**Comment by frgfm** [comment]
@nikokks for text recognition, we use cropped words from various types of documents, which sum up to about 11M images.
The bias is indeed around the choice of characters (European mostly) and the language (some sequences of characters are more frequent than others).

However, a while back, we started a fully synthetic approach (cf. `CharacterGenerator` and `WordGenerator`). So far, the results are not on par, but still very decent for a fully synthetic approach :)

**Comment by odulcy-mindee** [comment]
Training started on `Linked_Resnet50` (Tensorflow), we'll post the results soon :wink:

**Comment by felixdittrich92** [comment]
Closing because we track it in #1364
