### ISSUE TITLE
Orientation details are not available in Json exported

### ISSUE THREAD

**Issue by gnanads** [mindee/doctr#973]
### Discussed in https://github.com/mindee/doctr/discussions/971

<div type='discussions-op-text'>

<sup>Originally posted by **gnanads** July  1, 2022</sup>
Hi Team,

When I exported the ocr_predictor results, I found orientation and Language information are missing.

Below is the code snippet:

```
model = ocr_predictor('linknet_resnet18_rotation','crnn_vgg16_bn',pretrained=True,assume_straight_pages=False, preserve_aspect_ratio=True)
result = model([image])
export = result.export()
print(export)
```

Result json:
{'page_idx': 0, 'dimensions': (912, 617), 'orientation': {'value': None, 'confidence': None}, 'language': {'value': None, 'confidence': None}</div>

**Comment by nikokks** [comment]
Hello,

the function used to get the orientation of the document uses function with open CV. 
Why did you not used the angles'median of the larger sides of the bboxes ?
