### ISSUE TITLE
Turn off automatically download backbone model

### ISSUE THREAD

**Issue by bavo96** [mindee/doctr#991]
Hi team,

Why don't we use the `pretrained` flag instead of `pretrained_backbone` flag for using pretrained model in `backbone_fn` ? I have turned off the flag `pretrained` by passing the flag to the `ocr_predictor` but it keeps downloading the pretrained model for backbone and I have to modify the code manually. Can we combine those flags into one or pass the `pretrained_backbone` outside this function? 
![image](https://user-images.githubusercontent.com/27908949/179979379-6b6a65c0-73a9-42bf-8679-c889a38ec3ea.png)

Many thanks.

**Comment by frgfm** [comment]
Hello @bavo96 :wave: 

First, quick suggestions: 
- this is more of a question topic than bug reporting, so [GH discussions](https://github.com/mindee/doctr/discussions/new) are a better fit for this :)
- especially when sharing code, send the url with a reference or copy paste & format the code, but avoid screenshots :pray: 

Now, about your question:
- first off, you can pass `pretrained_backbone=False` to the model directly (though it's true that from the recognition_predictor it's not possible as is (feel free to open a PR if you want :))
- the reason we didn't consider this is that when not using a pretrained model, you are most likely training something if you're doing anything at all. In that case, having part of the network already trained on a relevant data distribution is useful. You can freeze the backbone and train only the later parts of the model to check results quickly :+1: 

I hope this helps, cheers :v:

**Comment by bavo96** [comment]
Hi @frgfm, so sorry about my posting, I'm still new to this repo and don't know where to post the question :( I'll post the reference to the code next time ❤️ Thanks for your suggestions. 
I don't mind if we use the pretrained backbone when training a model. But in reference (testing) phase, I want to load my trained model (by using `load_state_dict`) instead of downloading the pretrained model again. So in this case, the code will download a pretrained model (when creating a `doctr.models.ocr_predictor` object), and then I load my trained model (`reco_predictor.load_state_dict`), which is redundant and can be done by loading my trained model only. What do you think about this situation?

**Comment by frgfm** [comment]
Hi @bavo96 :wave: 

Oh don't misinterpret my previous message, there is no problem at all :) I prefer to share feedback so that you get more familiar with the OSS community :grin: 

> in reference (testing) phase, I want to load my trained model (by using load_state_dict) instead of downloading the pretrained model again

Ok, so if I get this right, you'd like to have no download whatsoever and load your local model checkpoint directly, correct?

**Comment by bavo96** [comment]
HI @frgfm 
That is exactly what I need right now :D

**Comment by frgfm** [comment]
Got it :+1: I'll stage this for the next release, and you'll get notified whenever a PR closes this issue!
